#include "syntax.h"

#include <ctype.h>
#include <regex.h>
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>

#include "tree_sitter/api.h"

// Generated by vendored tree-sitter grammar sources.
extern const TSLanguage *tree_sitter_c(void);
extern const TSLanguage *tree_sitter_bash(void);
extern const TSLanguage *tree_sitter_html(void);
extern const TSLanguage *tree_sitter_javascript(void);
extern const TSLanguage *tree_sitter_css(void);

enum editorSyntaxCaptureRole {
	EDITOR_SYNTAX_CAPTURE_ROLE_NONE = 0,
	EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_SCOPE,
	EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_DEFINITION,
	EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_REFERENCE,
	EDITOR_SYNTAX_CAPTURE_ROLE_INJECTION_CONTENT
};

struct editorSyntaxParsedTree {
	enum editorSyntaxLanguage language;
	TSParser *parser;
	TSTree *tree;
	TSRange *included_ranges;
	uint32_t included_range_count;
};

struct editorSyntaxState {
	enum editorSyntaxLanguage language;
	struct editorSyntaxParsedTree host;
	struct editorSyntaxParsedTree javascript_injection;
	struct editorSyntaxParsedTree css_injection;
	char *source_snapshot;
	size_t source_snapshot_len;
};

struct editorSyntaxQueryCacheEntry {
	int load_attempted;
	TSQuery *query;
	enum editorSyntaxHighlightClass *capture_classes;
	uint8_t *capture_roles;
	char **pattern_injection_languages;
	uint32_t capture_count;
	uint32_t pattern_count;
};

struct editorSyntaxLocalMark {
	TSNode node;
	int is_local;
};

struct editorSyntaxLocalsContext {
	struct editorSyntaxLocalMark *marks;
	int count;
	int cap;
};

struct editorSyntaxScopeInfo {
	TSNode node;
	int parent_idx;
	char **definitions;
	int def_count;
	int def_cap;
};

struct editorSyntaxCaptureVec {
	struct editorSyntaxCapture *items;
	int count;
	int cap;
};

struct editorSyntaxRangeVec {
	TSRange *items;
	uint32_t count;
	uint32_t cap;
};

struct editorSyntaxPredicateContext {
	const char *source;
	size_t source_len;
	const struct editorSyntaxLocalsContext *locals;
};

static struct editorSyntaxQueryCacheEntry g_c_highlight_query_cache = {0};
static struct editorSyntaxQueryCacheEntry g_shell_highlight_query_cache = {0};
static struct editorSyntaxQueryCacheEntry g_html_highlight_query_cache = {0};
static struct editorSyntaxQueryCacheEntry g_javascript_highlight_query_cache = {0};
static struct editorSyntaxQueryCacheEntry g_css_highlight_query_cache = {0};
static struct editorSyntaxQueryCacheEntry g_javascript_locals_query_cache = {0};
static struct editorSyntaxQueryCacheEntry g_html_injection_query_cache = {0};

static const char editor_builtin_c_highlights_query[] =
		"(comment) @comment\n"
		"(string_literal) @string\n"
		"(char_literal) @string\n"
		"(number_literal) @number\n"
		"[(true) (false)] @constant\n"
		"(primitive_type) @type\n"
		"(type_identifier) @type\n"
		"(call_expression function: (identifier) @function)\n"
		"(function_declarator (identifier) @function)\n"
		"[(preproc_include) (preproc_def) (preproc_function_def) (preproc_call)] @preprocessor\n"
		"[\"if\" \"else\" \"switch\" \"case\" \"default\" \"while\" \"for\" \"do\"\n"
		" \"return\" \"break\" \"continue\" \"goto\" \"typedef\" \"struct\" \"enum\" \"union\"\n"
		" \"sizeof\" \"static\" \"extern\" \"inline\" \"const\" \"volatile\"] @keyword\n";

static const char editor_builtin_shell_highlights_query[] =
		"(comment) @comment\n"
		"[(string) (raw_string) (heredoc_body) (heredoc_start)] @string\n"
		"(command_name) @command\n"
		"(function_definition name: (word) @function)\n"
		"(variable_name) @variable\n"
		"(file_descriptor) @number\n"
		"[\"if\" \"then\" \"else\" \"elif\" \"fi\" \"for\" \"in\" \"do\" \"done\"\n"
		" \"while\" \"until\" \"case\" \"esac\" \"function\"] @keyword\n"
		"[\"$\" \"&&\" \">\" \">>\" \"<\" \"|\"] @operator\n";

static const char editor_builtin_html_highlights_query[] =
		"(tag_name) @tag\n"
		"(attribute_name) @attribute\n"
		"(attribute_value) @string\n"
		"(comment) @comment\n"
		"[(\"<\") (\">\") (\"</\") (\"/>\")] @punctuation.bracket\n";

static const char editor_builtin_javascript_highlights_query[] =
		"(identifier) @variable\n"
		"(property_identifier) @property\n"
		"(comment) @comment\n"
		"[(string) (template_string)] @string\n"
		"(number) @number\n"
		"[(function_declaration name: (identifier) @function)]\n"
		"[(\"function\") (\"return\") (\"if\") (\"else\") (\"for\") (\"while\")] @keyword\n";

static const char editor_builtin_javascript_locals_query[] =
		"[(statement_block) (function_expression) (arrow_function)\n"
		" (function_declaration) (method_definition)] @local.scope\n"
		"(pattern/identifier) @local.definition\n"
		"(variable_declarator name: (identifier) @local.definition)\n"
		"(identifier) @local.reference\n";

static const char editor_builtin_css_highlights_query[] =
		"(comment) @comment\n"
		"(tag_name) @tag\n"
		"(property_name) @property\n"
		"(function_name) @function\n"
		"(string_value) @string\n"
		"[(integer_value) (float_value)] @number\n"
		"(attribute_name) @attribute\n"
		"(class_name) @property\n"
		"(id_name) @property\n"
		"(at_keyword) @keyword\n";

static const char editor_builtin_html_injections_query[] =
		"((script_element (raw_text) @injection.content)\n"
		" (#set! injection.language \"javascript\"))\n"
		"((style_element (raw_text) @injection.content)\n"
		" (#set! injection.language \"css\"))\n";

static const char *const g_c_highlight_query_paths[] = {
	"vendor/tree_sitter/grammars/c/queries/highlights.scm"
};

static const char *const g_shell_highlight_query_paths[] = {
	"vendor/tree_sitter/grammars/bash/queries/highlights.scm"
};

static const char *const g_html_highlight_query_paths[] = {
	"vendor/tree_sitter/grammars/html/queries/highlights.scm"
};

static const char *const g_javascript_highlight_query_paths[] = {
	"vendor/tree_sitter/grammars/javascript/queries/highlights.scm",
	"vendor/tree_sitter/grammars/javascript/queries/highlights-jsx.scm",
	"vendor/tree_sitter/grammars/javascript/queries/highlights-params.scm"
};

static const char *const g_javascript_locals_query_paths[] = {
	"vendor/tree_sitter/grammars/javascript/queries/locals.scm"
};

static const char *const g_css_highlight_query_paths[] = {
	"vendor/tree_sitter/grammars/css/queries/highlights.scm"
};

static const char *const g_html_injection_query_paths[] = {
	"vendor/tree_sitter/grammars/html/queries/injections.scm"
};

static int editorSyntaxStringEquals(const char *s, size_t len, const char *literal) {
	if (s == NULL || literal == NULL) {
		return 0;
	}
	size_t lit_len = strlen(literal);
	if (len != lit_len) {
		return 0;
	}
	return memcmp(s, literal, len) == 0;
}

static int editorSyntaxStringEqualsNoCase(const char *s, size_t len, const char *literal) {
	if (s == NULL || literal == NULL) {
		return 0;
	}
	size_t lit_len = strlen(literal);
	if (len != lit_len) {
		return 0;
	}
	return strncasecmp(s, literal, len) == 0;
}

static int editorSyntaxLengthFitsTreeSitter(size_t len) {
	return len <= UINT32_MAX;
}

static int editorSyntaxCaptureNameHasPrefix(const char *name, size_t len, const char *prefix) {
	size_t prefix_len = strlen(prefix);
	if (name == NULL || prefix == NULL || len < prefix_len) {
		return 0;
	}
	return strncmp(name, prefix, prefix_len) == 0;
}

static enum editorSyntaxHighlightClass editorSyntaxClassFromCaptureName(const char *name,
		size_t len) {
	if (name == NULL || len == 0) {
		return EDITOR_SYNTAX_HL_NONE;
	}

	if (editorSyntaxCaptureNameHasPrefix(name, len, "comment")) {
		return EDITOR_SYNTAX_HL_COMMENT;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "keyword")) {
		return EDITOR_SYNTAX_HL_KEYWORD;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "type") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "constructor") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "tag")) {
		return EDITOR_SYNTAX_HL_TYPE;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "function") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "command") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "label")) {
		return EDITOR_SYNTAX_HL_FUNCTION;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "string") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "character")) {
		return EDITOR_SYNTAX_HL_STRING;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "number") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "float")) {
		return EDITOR_SYNTAX_HL_NUMBER;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "variable.builtin") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "constant") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "boolean") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "property")) {
		return EDITOR_SYNTAX_HL_CONSTANT;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "attribute") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "preproc") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "preprocessor")) {
		return EDITOR_SYNTAX_HL_PREPROCESSOR;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "operator")) {
		return EDITOR_SYNTAX_HL_OPERATOR;
	}
	if (editorSyntaxCaptureNameHasPrefix(name, len, "punctuation") ||
			editorSyntaxCaptureNameHasPrefix(name, len, "delimiter")) {
		return EDITOR_SYNTAX_HL_PUNCTUATION;
	}

	return EDITOR_SYNTAX_HL_NONE;
}

static char *editorSyntaxReadFileDup(const char *path, size_t *len_out) {
	if (len_out != NULL) {
		*len_out = 0;
	}
	if (path == NULL) {
		return NULL;
	}

	FILE *fp = fopen(path, "rb");
	if (fp == NULL) {
		return NULL;
	}

	size_t cap = 1024;
	size_t len = 0;
	char *buf = malloc(cap);
	if (buf == NULL) {
		fclose(fp);
		return NULL;
	}

	for (;;) {
		if (len + 1 >= cap) {
			size_t new_cap = cap * 2;
			if (new_cap <= cap) {
				free(buf);
				fclose(fp);
				return NULL;
			}
			char *grown = realloc(buf, new_cap);
			if (grown == NULL) {
				free(buf);
				fclose(fp);
				return NULL;
			}
			buf = grown;
			cap = new_cap;
		}

		size_t remaining = cap - len - 1;
		size_t nread = fread(buf + len, 1, remaining, fp);
		len += nread;
		if (nread < remaining) {
			if (ferror(fp)) {
				free(buf);
				fclose(fp);
				return NULL;
			}
			break;
		}
	}

	fclose(fp);
	buf[len] = '\0';
	if (len_out != NULL) {
		*len_out = len;
	}
	return buf;
}

static int editorSyntaxAppendBytes(char **buf, size_t *len, size_t *cap,
		const char *chunk, size_t chunk_len) {
	if (buf == NULL || len == NULL || cap == NULL || (chunk_len > 0 && chunk == NULL)) {
		return 0;
	}

	size_t needed = *len + chunk_len + 1;
	if (needed > *cap) {
		size_t new_cap = *cap == 0 ? 1024 : *cap;
		while (new_cap < needed) {
			size_t grown = new_cap * 2;
			if (grown <= new_cap) {
				return 0;
			}
			new_cap = grown;
		}
		char *grown_buf = realloc(*buf, new_cap);
		if (grown_buf == NULL) {
			return 0;
		}
		*buf = grown_buf;
		*cap = new_cap;
	}

	if (chunk_len > 0) {
		memcpy(*buf + *len, chunk, chunk_len);
		*len += chunk_len;
	}
	(*buf)[*len] = '\0';
	return 1;
}

static char *editorSyntaxReadFilesConcat(const char *const *paths, int path_count,
		size_t *len_out) {
	if (len_out != NULL) {
		*len_out = 0;
	}
	if (paths == NULL || path_count <= 0) {
		return NULL;
	}

	char *buf = NULL;
	size_t len = 0;
	size_t cap = 0;
	int loaded_any = 0;

	for (int i = 0; i < path_count; i++) {
		size_t file_len = 0;
		char *file = editorSyntaxReadFileDup(paths[i], &file_len);
		if (file == NULL) {
			continue;
		}

		if (!editorSyntaxAppendBytes(&buf, &len, &cap, file, file_len)) {
			free(file);
			free(buf);
			return NULL;
		}
		if (!editorSyntaxAppendBytes(&buf, &len, &cap, "\n", 1)) {
			free(file);
			free(buf);
			return NULL;
		}
		loaded_any = 1;
		free(file);
	}

	if (!loaded_any) {
		free(buf);
		return NULL;
	}
	if (len_out != NULL) {
		*len_out = len;
	}
	return buf;
}

static const TSLanguage *editorSyntaxLanguageObject(enum editorSyntaxLanguage language) {
	switch (language) {
		case EDITOR_SYNTAX_C:
			return tree_sitter_c();
		case EDITOR_SYNTAX_SHELL:
			return tree_sitter_bash();
		case EDITOR_SYNTAX_HTML:
			return tree_sitter_html();
		case EDITOR_SYNTAX_JAVASCRIPT:
			return tree_sitter_javascript();
		case EDITOR_SYNTAX_CSS:
			return tree_sitter_css();
		case EDITOR_SYNTAX_NONE:
		default:
			return NULL;
	}
}

static int editorSyntaxCompileQuery(enum editorSyntaxLanguage language,
		const char *query_source, size_t query_len, TSQuery **query_out) {
	const TSLanguage *ts_language = editorSyntaxLanguageObject(language);
	if (ts_language == NULL || query_source == NULL || query_out == NULL ||
			!editorSyntaxLengthFitsTreeSitter(query_len)) {
		return 0;
	}

	uint32_t error_offset = 0;
	TSQueryError error_type = TSQueryErrorNone;
	TSQuery *query = ts_query_new(ts_language, query_source, (uint32_t)query_len,
			&error_offset, &error_type);
	if (query == NULL) {
		(void)error_offset;
		(void)error_type;
		return 0;
	}

	*query_out = query;
	return 1;
}

static int editorSyntaxPopulateCaptureClasses(TSQuery *query,
		enum editorSyntaxHighlightClass **capture_classes_out, uint32_t *capture_count_out) {
	if (capture_classes_out == NULL || capture_count_out == NULL || query == NULL) {
		return 0;
	}
	*capture_classes_out = NULL;
	*capture_count_out = 0;

	uint32_t capture_count = ts_query_capture_count(query);
	enum editorSyntaxHighlightClass *capture_classes = NULL;
	if (capture_count > 0) {
		size_t bytes = (size_t)capture_count * sizeof(*capture_classes);
		capture_classes = malloc(bytes);
		if (capture_classes == NULL) {
			return 0;
		}
		for (uint32_t i = 0; i < capture_count; i++) {
			capture_classes[i] = EDITOR_SYNTAX_HL_NONE;
		}
		for (uint32_t i = 0; i < capture_count; i++) {
			uint32_t name_len = 0;
			const char *name = ts_query_capture_name_for_id(query, i, &name_len);
			capture_classes[i] = editorSyntaxClassFromCaptureName(name, name_len);
		}
	}

	*capture_classes_out = capture_classes;
	*capture_count_out = capture_count;
	return 1;
}

static int editorSyntaxPopulateLocalsCaptureRoles(TSQuery *query, uint8_t **capture_roles_out,
		uint32_t *capture_count_out) {
	if (query == NULL || capture_roles_out == NULL || capture_count_out == NULL) {
		return 0;
	}
	*capture_roles_out = NULL;
	*capture_count_out = 0;

	uint32_t capture_count = ts_query_capture_count(query);
	uint8_t *capture_roles = NULL;
	if (capture_count > 0) {
		capture_roles = calloc(capture_count, sizeof(*capture_roles));
		if (capture_roles == NULL) {
			return 0;
		}

		for (uint32_t i = 0; i < capture_count; i++) {
			uint32_t name_len = 0;
			const char *name = ts_query_capture_name_for_id(query, i, &name_len);
			if (editorSyntaxStringEquals(name, name_len, "local.scope")) {
				capture_roles[i] = EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_SCOPE;
			} else if (editorSyntaxStringEquals(name, name_len, "local.definition")) {
				capture_roles[i] = EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_DEFINITION;
			} else if (editorSyntaxStringEquals(name, name_len, "local.reference")) {
				capture_roles[i] = EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_REFERENCE;
			}
		}
	}

	*capture_roles_out = capture_roles;
	*capture_count_out = capture_count;
	return 1;
}

static int editorSyntaxPopulateInjectionCaptureRoles(TSQuery *query, uint8_t **capture_roles_out,
		uint32_t *capture_count_out) {
	if (query == NULL || capture_roles_out == NULL || capture_count_out == NULL) {
		return 0;
	}
	*capture_roles_out = NULL;
	*capture_count_out = 0;

	uint32_t capture_count = ts_query_capture_count(query);
	uint8_t *capture_roles = NULL;
	if (capture_count > 0) {
		capture_roles = calloc(capture_count, sizeof(*capture_roles));
		if (capture_roles == NULL) {
			return 0;
		}

		for (uint32_t i = 0; i < capture_count; i++) {
			uint32_t name_len = 0;
			const char *name = ts_query_capture_name_for_id(query, i, &name_len);
			if (editorSyntaxCaptureNameHasPrefix(name, name_len, "injection.content")) {
				capture_roles[i] = EDITOR_SYNTAX_CAPTURE_ROLE_INJECTION_CONTENT;
			}
		}
	}

	*capture_roles_out = capture_roles;
	*capture_count_out = capture_count;
	return 1;
}

static int editorSyntaxPopulateInjectionPatternLanguages(TSQuery *query,
		char ***languages_out, uint32_t *pattern_count_out) {
	if (query == NULL || languages_out == NULL || pattern_count_out == NULL) {
		return 0;
	}
	*languages_out = NULL;
	*pattern_count_out = 0;

	uint32_t pattern_count = ts_query_pattern_count(query);
	char **languages = NULL;
	if (pattern_count > 0) {
		languages = calloc(pattern_count, sizeof(*languages));
		if (languages == NULL) {
			return 0;
		}
	}

	for (uint32_t pattern_idx = 0; pattern_idx < pattern_count; pattern_idx++) {
		uint32_t step_count = 0;
		const TSQueryPredicateStep *steps = ts_query_predicates_for_pattern(query, pattern_idx,
				&step_count);
		if (steps == NULL || step_count == 0) {
			continue;
		}

		uint32_t i = 0;
		while (i < step_count) {
			uint32_t start = i;
			while (i < step_count && steps[i].type != TSQueryPredicateStepTypeDone) {
				i++;
			}
			uint32_t end = i;
			if (end > start && steps[start].type == TSQueryPredicateStepTypeString) {
				uint32_t cmd_len = 0;
				const char *cmd = ts_query_string_value_for_id(query, steps[start].value_id,
						&cmd_len);
				if (editorSyntaxStringEquals(cmd, cmd_len, "set!") && end - start >= 3 &&
						steps[start + 1].type == TSQueryPredicateStepTypeString &&
						steps[start + 2].type == TSQueryPredicateStepTypeString) {
					uint32_t key_len = 0;
					const char *key = ts_query_string_value_for_id(query,
							steps[start + 1].value_id, &key_len);
					if (editorSyntaxStringEquals(key, key_len, "injection.language")) {
						uint32_t value_len = 0;
						const char *value = ts_query_string_value_for_id(query,
								steps[start + 2].value_id, &value_len);
						char *dup = malloc((size_t)value_len + 1);
						if (dup == NULL) {
							for (uint32_t j = 0; j < pattern_count; j++) {
								free(languages[j]);
							}
							free(languages);
							return 0;
						}
						memcpy(dup, value, value_len);
						dup[value_len] = '\0';
						free(languages[pattern_idx]);
						languages[pattern_idx] = dup;
					}
				}
			}
			i++;
		}
	}

	*languages_out = languages;
	*pattern_count_out = pattern_count;
	return 1;
}

static void editorSyntaxClearQueryCacheEntry(struct editorSyntaxQueryCacheEntry *cache) {
	if (cache == NULL) {
		return;
	}
	if (cache->query != NULL) {
		ts_query_delete(cache->query);
		cache->query = NULL;
	}
	free(cache->capture_classes);
	cache->capture_classes = NULL;
	free(cache->capture_roles);
	cache->capture_roles = NULL;
	if (cache->pattern_injection_languages != NULL) {
		for (uint32_t i = 0; i < cache->pattern_count; i++) {
			free(cache->pattern_injection_languages[i]);
		}
	}
	free(cache->pattern_injection_languages);
	cache->pattern_injection_languages = NULL;
	cache->capture_count = 0;
	cache->pattern_count = 0;
	cache->load_attempted = 0;
}

static int editorSyntaxEnsureQueryCache(struct editorSyntaxQueryCacheEntry *cache,
		enum editorSyntaxLanguage language,
		const char *const *query_paths,
		int query_path_count,
		const char *fallback_query,
		int want_capture_classes,
		int want_locals_roles,
		int want_injection_roles,
		int want_injection_languages) {
	if (cache == NULL || (query_paths == NULL && fallback_query == NULL)) {
		return 0;
	}
	if (cache->load_attempted) {
		return cache->query != NULL;
	}
	cache->load_attempted = 1;

	TSQuery *query = NULL;
	size_t query_len = 0;
	char *file_query = editorSyntaxReadFilesConcat(query_paths, query_path_count, &query_len);
	if (file_query != NULL) {
		(void)editorSyntaxCompileQuery(language, file_query, query_len, &query);
		free(file_query);
	}

	if (query == NULL && fallback_query != NULL) {
		(void)editorSyntaxCompileQuery(language, fallback_query, strlen(fallback_query), &query);
	}
	if (query == NULL) {
		return 0;
	}

	enum editorSyntaxHighlightClass *capture_classes = NULL;
	uint8_t *capture_roles = NULL;
	char **pattern_languages = NULL;
	uint32_t capture_count = 0;
	uint32_t pattern_count = 0;

	if (want_capture_classes &&
			!editorSyntaxPopulateCaptureClasses(query, &capture_classes, &capture_count)) {
		ts_query_delete(query);
		return 0;
	}

	if (want_locals_roles &&
			!editorSyntaxPopulateLocalsCaptureRoles(query, &capture_roles, &capture_count)) {
		free(capture_classes);
		ts_query_delete(query);
		return 0;
	}

	if (want_injection_roles &&
			!editorSyntaxPopulateInjectionCaptureRoles(query, &capture_roles, &capture_count)) {
		free(capture_classes);
		ts_query_delete(query);
		return 0;
	}

	if (want_injection_languages &&
			!editorSyntaxPopulateInjectionPatternLanguages(query, &pattern_languages,
					&pattern_count)) {
		free(capture_classes);
		free(capture_roles);
		ts_query_delete(query);
		return 0;
	}

	cache->query = query;
	cache->capture_classes = capture_classes;
	cache->capture_roles = capture_roles;
	cache->pattern_injection_languages = pattern_languages;
	cache->capture_count = capture_count;
	cache->pattern_count = pattern_count;
	return 1;
}

static int editorSyntaxEnsureHighlightQuery(enum editorSyntaxLanguage language) {
	switch (language) {
		case EDITOR_SYNTAX_C:
			return editorSyntaxEnsureQueryCache(&g_c_highlight_query_cache, EDITOR_SYNTAX_C,
					g_c_highlight_query_paths,
					(int)(sizeof(g_c_highlight_query_paths) / sizeof(g_c_highlight_query_paths[0])),
					editor_builtin_c_highlights_query,
					1, 0, 0, 0);
		case EDITOR_SYNTAX_SHELL:
			return editorSyntaxEnsureQueryCache(&g_shell_highlight_query_cache,
					EDITOR_SYNTAX_SHELL,
					g_shell_highlight_query_paths,
					(int)(sizeof(g_shell_highlight_query_paths) /
						sizeof(g_shell_highlight_query_paths[0])),
					editor_builtin_shell_highlights_query,
					1, 0, 0, 0);
		case EDITOR_SYNTAX_HTML:
			return editorSyntaxEnsureQueryCache(&g_html_highlight_query_cache, EDITOR_SYNTAX_HTML,
					g_html_highlight_query_paths,
					(int)(sizeof(g_html_highlight_query_paths) /
						sizeof(g_html_highlight_query_paths[0])),
					editor_builtin_html_highlights_query,
					1, 0, 0, 0);
		case EDITOR_SYNTAX_JAVASCRIPT:
			return editorSyntaxEnsureQueryCache(&g_javascript_highlight_query_cache,
					EDITOR_SYNTAX_JAVASCRIPT,
					g_javascript_highlight_query_paths,
					(int)(sizeof(g_javascript_highlight_query_paths) /
						sizeof(g_javascript_highlight_query_paths[0])),
					editor_builtin_javascript_highlights_query,
					1, 0, 0, 0);
		case EDITOR_SYNTAX_CSS:
			return editorSyntaxEnsureQueryCache(&g_css_highlight_query_cache,
					EDITOR_SYNTAX_CSS,
					g_css_highlight_query_paths,
					(int)(sizeof(g_css_highlight_query_paths) /
						sizeof(g_css_highlight_query_paths[0])),
					editor_builtin_css_highlights_query,
					1, 0, 0, 0);
		case EDITOR_SYNTAX_NONE:
		default:
			return 0;
	}
}

static int editorSyntaxEnsureLocalsQuery(enum editorSyntaxLanguage language) {
	if (language != EDITOR_SYNTAX_JAVASCRIPT) {
		return 0;
	}
	return editorSyntaxEnsureQueryCache(&g_javascript_locals_query_cache,
			EDITOR_SYNTAX_JAVASCRIPT,
			g_javascript_locals_query_paths,
			(int)(sizeof(g_javascript_locals_query_paths) /
				sizeof(g_javascript_locals_query_paths[0])),
			editor_builtin_javascript_locals_query,
			0, 1, 0, 0);
}

static int editorSyntaxEnsureHtmlInjectionQuery(void) {
	return editorSyntaxEnsureQueryCache(&g_html_injection_query_cache,
			EDITOR_SYNTAX_HTML,
			g_html_injection_query_paths,
			(int)(sizeof(g_html_injection_query_paths) /
				sizeof(g_html_injection_query_paths[0])),
			editor_builtin_html_injections_query,
			0, 0, 1, 1);
}

static const struct editorSyntaxQueryCacheEntry *editorSyntaxHighlightQueryCacheForLanguage(
		enum editorSyntaxLanguage language) {
	switch (language) {
		case EDITOR_SYNTAX_C:
			return &g_c_highlight_query_cache;
		case EDITOR_SYNTAX_SHELL:
			return &g_shell_highlight_query_cache;
		case EDITOR_SYNTAX_HTML:
			return &g_html_highlight_query_cache;
		case EDITOR_SYNTAX_JAVASCRIPT:
			return &g_javascript_highlight_query_cache;
		case EDITOR_SYNTAX_CSS:
			return &g_css_highlight_query_cache;
		case EDITOR_SYNTAX_NONE:
		default:
			return NULL;
	}
}

static const struct editorSyntaxQueryCacheEntry *editorSyntaxLocalsQueryCacheForLanguage(
		enum editorSyntaxLanguage language) {
	if (language == EDITOR_SYNTAX_JAVASCRIPT) {
		return &g_javascript_locals_query_cache;
	}
	return NULL;
}

static int editorSyntaxIsShellInterpreterName(const char *token, size_t len) {
	return (len == 2 && strncasecmp(token, "sh", 2) == 0) ||
			(len == 4 && strncasecmp(token, "bash", 4) == 0) ||
			(len == 3 && strncasecmp(token, "zsh", 3) == 0) ||
			(len == 3 && strncasecmp(token, "ksh", 3) == 0);
}

static int editorSyntaxTokenFromLine(const char *line, size_t line_len, size_t *idx,
		const char **token_out, size_t *token_len_out) {
	if (line == NULL || idx == NULL || token_out == NULL || token_len_out == NULL) {
		return 0;
	}

	size_t i = *idx;
	while (i < line_len && isspace((unsigned char)line[i])) {
		i++;
	}
	if (i >= line_len) {
		*idx = i;
		return 0;
	}

	size_t start = i;
	while (i < line_len && !isspace((unsigned char)line[i])) {
		i++;
	}

	*idx = i;
	*token_out = &line[start];
	*token_len_out = i - start;
	return 1;
}

static enum editorSyntaxLanguage editorSyntaxDetectLanguageFromShebang(const char *first_line) {
	if (first_line == NULL || first_line[0] != '#' || first_line[1] != '!') {
		return EDITOR_SYNTAX_NONE;
	}

	size_t line_len = strlen(first_line);
	size_t idx = 2;
	const char *token = NULL;
	size_t token_len = 0;
	if (!editorSyntaxTokenFromLine(first_line, line_len, &idx, &token, &token_len)) {
		return EDITOR_SYNTAX_NONE;
	}

	const char *base = token;
	for (size_t i = 0; i < token_len; i++) {
		if (token[i] == '/') {
			base = &token[i + 1];
		}
	}
	size_t base_len = token_len - (size_t)(base - token);

	if (editorSyntaxIsShellInterpreterName(base, base_len)) {
		return EDITOR_SYNTAX_SHELL;
	}

	if (base_len == 3 && strncasecmp(base, "env", 3) == 0) {
		for (;;) {
			if (!editorSyntaxTokenFromLine(first_line, line_len, &idx, &token, &token_len)) {
				break;
			}
			if (token_len > 0 && token[0] == '-') {
				continue;
			}

			base = token;
			for (size_t i = 0; i < token_len; i++) {
				if (token[i] == '/') {
					base = &token[i + 1];
				}
			}
			base_len = token_len - (size_t)(base - token);
			if (editorSyntaxIsShellInterpreterName(base, base_len)) {
				return EDITOR_SYNTAX_SHELL;
			}
			break;
		}
	}

	return EDITOR_SYNTAX_NONE;
}

static int editorSyntaxFilenameIsExtensionless(const char *filename) {
	if (filename == NULL || filename[0] == '\0') {
		return 1;
	}

	const char *base = strrchr(filename, '/');
	if (base != NULL) {
		base++;
	} else {
		base = filename;
	}
	if (base[0] == '\0') {
		return 0;
	}
	if (strchr(base, '.') == NULL) {
		return 1;
	}
	if (base[0] == '.' && strchr(base + 1, '.') == NULL) {
		return 1;
	}
	return 0;
}

enum editorSyntaxLanguage editorSyntaxDetectLanguageFromFilename(const char *filename) {
	if (filename == NULL || filename[0] == '\0') {
		return EDITOR_SYNTAX_NONE;
	}

	const char *dot = strrchr(filename, '.');
	if (dot != NULL && (strcmp(dot, ".c") == 0 || strcmp(dot, ".h") == 0)) {
		return EDITOR_SYNTAX_C;
	}
	if (dot != NULL &&
			(strcmp(dot, ".sh") == 0 || strcmp(dot, ".bash") == 0 ||
					strcmp(dot, ".zsh") == 0 || strcmp(dot, ".ksh") == 0)) {
		return EDITOR_SYNTAX_SHELL;
	}
	if (dot != NULL &&
			(strcmp(dot, ".html") == 0 || strcmp(dot, ".htm") == 0 ||
					strcmp(dot, ".xhtml") == 0)) {
		return EDITOR_SYNTAX_HTML;
	}
	if (dot != NULL &&
			(strcmp(dot, ".js") == 0 || strcmp(dot, ".mjs") == 0 ||
					strcmp(dot, ".cjs") == 0 || strcmp(dot, ".jsx") == 0)) {
		return EDITOR_SYNTAX_JAVASCRIPT;
	}
	if (dot != NULL && (strcmp(dot, ".css") == 0 || strcmp(dot, ".scss") == 0)) {
		return EDITOR_SYNTAX_CSS;
	}

	const char *base = strrchr(filename, '/');
	if (base != NULL) {
		base++;
	} else {
		base = filename;
	}
	if (strcmp(base, ".bashrc") == 0 || strcmp(base, ".zshrc") == 0 ||
			strcmp(base, ".profile") == 0 || strcmp(base, ".bash_profile") == 0 ||
			strcmp(base, ".bash_login") == 0 || strcmp(base, ".kshrc") == 0) {
		return EDITOR_SYNTAX_SHELL;
	}

	return EDITOR_SYNTAX_NONE;
}

enum editorSyntaxLanguage editorSyntaxDetectLanguageFromFilenameAndFirstLine(
		const char *filename, const char *first_line) {
	enum editorSyntaxLanguage from_filename = editorSyntaxDetectLanguageFromFilename(filename);
	if (from_filename != EDITOR_SYNTAX_NONE) {
		return from_filename;
	}
	if (!editorSyntaxFilenameIsExtensionless(filename)) {
		return EDITOR_SYNTAX_NONE;
	}

	return editorSyntaxDetectLanguageFromShebang(first_line);
}

static void editorSyntaxParsedTreeInit(struct editorSyntaxParsedTree *parsed,
		enum editorSyntaxLanguage language) {
	if (parsed == NULL) {
		return;
	}
	parsed->language = language;
	parsed->parser = NULL;
	parsed->tree = NULL;
	parsed->included_ranges = NULL;
	parsed->included_range_count = 0;
}

static int editorSyntaxParsedTreeCreateParser(struct editorSyntaxParsedTree *parsed,
		enum editorSyntaxLanguage language) {
	if (parsed == NULL) {
		return 0;
	}
	const TSLanguage *ts_language = editorSyntaxLanguageObject(language);
	if (ts_language == NULL) {
		return 0;
	}

	parsed->language = language;
	parsed->parser = ts_parser_new();
	if (parsed->parser == NULL) {
		return 0;
	}
	if (!ts_parser_set_language(parsed->parser, ts_language)) {
		ts_parser_delete(parsed->parser);
		parsed->parser = NULL;
		return 0;
	}
	return 1;
}

static void editorSyntaxParsedTreeDestroy(struct editorSyntaxParsedTree *parsed) {
	if (parsed == NULL) {
		return;
	}
	if (parsed->tree != NULL) {
		ts_tree_delete(parsed->tree);
		parsed->tree = NULL;
	}
	if (parsed->parser != NULL) {
		ts_parser_delete(parsed->parser);
		parsed->parser = NULL;
	}
	free(parsed->included_ranges);
	parsed->included_ranges = NULL;
	parsed->included_range_count = 0;
}

static int editorSyntaxParsedTreeSetIncludedRanges(struct editorSyntaxParsedTree *parsed,
		const TSRange *ranges,
		uint32_t range_count) {
	if (parsed == NULL || parsed->parser == NULL) {
		return 0;
	}

	TSRange *owned = NULL;
	if (range_count > 0) {
		size_t bytes = (size_t)range_count * sizeof(*owned);
		owned = malloc(bytes);
		if (owned == NULL) {
			return 0;
		}
		memcpy(owned, ranges, bytes);
	}

	if (!ts_parser_set_included_ranges(parsed->parser, owned, range_count)) {
		free(owned);
		return 0;
	}

	free(parsed->included_ranges);
	parsed->included_ranges = owned;
	parsed->included_range_count = range_count;
	return 1;
}

static int editorSyntaxParsedTreeParse(struct editorSyntaxParsedTree *parsed,
		const char *source,
		size_t len,
		int incremental) {
	if (parsed == NULL || parsed->parser == NULL || source == NULL ||
			!editorSyntaxLengthFitsTreeSitter(len)) {
		return 0;
	}

	TSTree *old_tree = incremental ? parsed->tree : NULL;
	TSTree *new_tree = ts_parser_parse_string(parsed->parser, old_tree, source, (uint32_t)len);
	if (new_tree == NULL) {
		return 0;
	}

	if (parsed->tree != NULL) {
		ts_tree_delete(parsed->tree);
	}
	parsed->tree = new_tree;
	return 1;
}

static int editorSyntaxNodeContains(TSNode outer, TSNode inner) {
	uint32_t outer_start = ts_node_start_byte(outer);
	uint32_t outer_end = ts_node_end_byte(outer);
	uint32_t inner_start = ts_node_start_byte(inner);
	uint32_t inner_end = ts_node_end_byte(inner);
	return outer_start <= inner_start && outer_end >= inner_end;
}

static uint32_t editorSyntaxNodeSpan(TSNode node) {
	uint32_t start = ts_node_start_byte(node);
	uint32_t end = ts_node_end_byte(node);
	if (end < start) {
		return 0;
	}
	return end - start;
}

static int editorSyntaxNodeText(const char *source, size_t source_len, TSNode node,
		const char **text_out, size_t *len_out) {
	if (source == NULL || text_out == NULL || len_out == NULL) {
		return 0;
	}

	uint32_t start = ts_node_start_byte(node);
	uint32_t end = ts_node_end_byte(node);
	if (end < start) {
		return 0;
	}
	if ((size_t)end > source_len) {
		return 0;
	}

	*text_out = source + start;
	*len_out = (size_t)(end - start);
	return 1;
}

static int editorSyntaxNodeArrayAppend(TSNode **items, int *count, int *cap, TSNode node) {
	if (items == NULL || count == NULL || cap == NULL) {
		return 0;
	}
	if (*count >= *cap) {
		int new_cap = *cap == 0 ? 16 : *cap * 2;
		if (new_cap <= *cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(**items);
		TSNode *grown = realloc(*items, bytes);
		if (grown == NULL) {
			return 0;
		}
		*items = grown;
		*cap = new_cap;
	}
	(*items)[*count] = node;
	(*count)++;
	return 1;
}

static void editorSyntaxLocalsContextInit(struct editorSyntaxLocalsContext *ctx) {
	if (ctx == NULL) {
		return;
	}
	ctx->marks = NULL;
	ctx->count = 0;
	ctx->cap = 0;
}

static void editorSyntaxLocalsContextFree(struct editorSyntaxLocalsContext *ctx) {
	if (ctx == NULL) {
		return;
	}
	free(ctx->marks);
	ctx->marks = NULL;
	ctx->count = 0;
	ctx->cap = 0;
}

static int editorSyntaxLocalsContextMarkNode(struct editorSyntaxLocalsContext *ctx,
		TSNode node,
		int is_local) {
	if (ctx == NULL) {
		return 0;
	}
	for (int i = 0; i < ctx->count; i++) {
		if (ts_node_eq(ctx->marks[i].node, node)) {
			if (is_local) {
				ctx->marks[i].is_local = 1;
			}
			return 1;
		}
	}

	if (ctx->count >= ctx->cap) {
		int new_cap = ctx->cap == 0 ? 32 : ctx->cap * 2;
		if (new_cap <= ctx->cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*ctx->marks);
		struct editorSyntaxLocalMark *grown = realloc(ctx->marks, bytes);
		if (grown == NULL) {
			return 0;
		}
		ctx->marks = grown;
		ctx->cap = new_cap;
	}

	ctx->marks[ctx->count].node = node;
	ctx->marks[ctx->count].is_local = is_local ? 1 : 0;
	ctx->count++;
	return 1;
}

static int editorSyntaxLocalsContextNodeIsLocal(const struct editorSyntaxLocalsContext *ctx,
		TSNode node) {
	if (ctx == NULL) {
		return 0;
	}
	for (int i = 0; i < ctx->count; i++) {
		if (ts_node_eq(ctx->marks[i].node, node)) {
			return ctx->marks[i].is_local != 0;
		}
	}
	return 0;
}

static int editorSyntaxScopeAddDefinition(struct editorSyntaxScopeInfo *scope,
		const char *name,
		size_t name_len) {
	if (scope == NULL || name == NULL) {
		return 0;
	}

	for (int i = 0; i < scope->def_count; i++) {
		if (strlen(scope->definitions[i]) == name_len &&
				memcmp(scope->definitions[i], name, name_len) == 0) {
			return 1;
		}
	}

	if (scope->def_count >= scope->def_cap) {
		int new_cap = scope->def_cap == 0 ? 8 : scope->def_cap * 2;
		if (new_cap <= scope->def_cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*scope->definitions);
		char **grown = realloc(scope->definitions, bytes);
		if (grown == NULL) {
			return 0;
		}
		scope->definitions = grown;
		scope->def_cap = new_cap;
	}

	char *dup = malloc(name_len + 1);
	if (dup == NULL) {
		return 0;
	}
	memcpy(dup, name, name_len);
	dup[name_len] = '\0';
	
	scope->definitions[scope->def_count] = dup;
	scope->def_count++;
	return 1;
}

static int editorSyntaxScopeHasDefinition(const struct editorSyntaxScopeInfo *scope,
		const char *name,
		size_t name_len) {
	if (scope == NULL || name == NULL) {
		return 0;
	}
	for (int i = 0; i < scope->def_count; i++) {
		if (strlen(scope->definitions[i]) == name_len &&
				memcmp(scope->definitions[i], name, name_len) == 0) {
			return 1;
		}
	}
	return 0;
}

static void editorSyntaxScopeInfoFree(struct editorSyntaxScopeInfo *scopes, int scope_count) {
	if (scopes == NULL) {
		return;
	}
	for (int i = 0; i < scope_count; i++) {
		for (int j = 0; j < scopes[i].def_count; j++) {
			free(scopes[i].definitions[j]);
		}
		free(scopes[i].definitions);
	}
	free(scopes);
}

static int editorSyntaxFindInnermostScope(const struct editorSyntaxScopeInfo *scopes,
		int scope_count,
		TSNode node) {
	int best_idx = -1;
	uint32_t best_span = UINT32_MAX;
	for (int i = 0; i < scope_count; i++) {
		if (!editorSyntaxNodeContains(scopes[i].node, node)) {
			continue;
		}
		uint32_t span = editorSyntaxNodeSpan(scopes[i].node);
		if (span < best_span) {
			best_span = span;
			best_idx = i;
		}
	}
	return best_idx;
}

static int editorSyntaxBuildLocalsContext(const TSTree *tree,
		enum editorSyntaxLanguage language,
		const char *source,
		size_t source_len,
		struct editorSyntaxLocalsContext *ctx_out) {
	if (ctx_out == NULL) {
		return 0;
	}
	editorSyntaxLocalsContextInit(ctx_out);
	if (tree == NULL || source == NULL) {
		return 1;
	}
	if (!editorSyntaxEnsureLocalsQuery(language)) {
		return 1;
	}

	const struct editorSyntaxQueryCacheEntry *cache =
			editorSyntaxLocalsQueryCacheForLanguage(language);
	if (cache == NULL || cache->query == NULL || cache->capture_roles == NULL) {
		return 1;
	}

	TSQueryCursor *cursor = ts_query_cursor_new();
	if (cursor == NULL) {
		return 0;
	}

	TSNode root = ts_tree_root_node(tree);
	ts_query_cursor_exec(cursor, cache->query, root);

	TSNode *scope_nodes = NULL;
	TSNode *definition_nodes = NULL;
	TSNode *reference_nodes = NULL;
	int scope_count = 0;
	int scope_cap = 0;
	int definition_count = 0;
	int definition_cap = 0;
	int reference_count = 0;
	int reference_cap = 0;

	TSQueryMatch match;
	while (ts_query_cursor_next_match(cursor, &match)) {
		for (uint16_t capture_idx = 0; capture_idx < match.capture_count; capture_idx++) {
			TSQueryCapture capture = match.captures[capture_idx];
			if (capture.index >= cache->capture_count) {
				continue;
			}
			uint8_t role = cache->capture_roles[capture.index];
			if (role == EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_SCOPE) {
				if (!editorSyntaxNodeArrayAppend(&scope_nodes, &scope_count, &scope_cap,
							capture.node)) {
					goto oom;
				}
			} else if (role == EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_DEFINITION) {
				if (!editorSyntaxNodeArrayAppend(&definition_nodes, &definition_count,
							&definition_cap, capture.node)) {
					goto oom;
				}
			} else if (role == EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_REFERENCE) {
				if (!editorSyntaxNodeArrayAppend(&reference_nodes, &reference_count,
							&reference_cap, capture.node)) {
					goto oom;
				}
			}
		}
	}

	if (!editorSyntaxNodeArrayAppend(&scope_nodes, &scope_count, &scope_cap, root)) {
		goto oom;
	}

	struct editorSyntaxScopeInfo *scopes = calloc((size_t)scope_count, sizeof(*scopes));
	if (scopes == NULL) {
		goto oom;
	}

	for (int i = 0; i < scope_count; i++) {
		scopes[i].node = scope_nodes[i];
		scopes[i].parent_idx = -1;
		scopes[i].definitions = NULL;
		scopes[i].def_count = 0;
		scopes[i].def_cap = 0;
	}

	for (int i = 0; i < scope_count; i++) {
		uint32_t span_i = editorSyntaxNodeSpan(scopes[i].node);
		uint32_t best_span = UINT32_MAX;
		int best_parent = -1;
		for (int j = 0; j < scope_count; j++) {
			if (i == j) {
				continue;
			}
			if (!editorSyntaxNodeContains(scopes[j].node, scopes[i].node)) {
				continue;
			}
			uint32_t span_j = editorSyntaxNodeSpan(scopes[j].node);
			if (span_j <= span_i) {
				continue;
			}
			if (span_j < best_span) {
				best_span = span_j;
				best_parent = j;
			}
		}
		scopes[i].parent_idx = best_parent;
	}

	for (int i = 0; i < definition_count; i++) {
		const char *text = NULL;
		size_t text_len = 0;
		if (!editorSyntaxNodeText(source, source_len, definition_nodes[i], &text, &text_len) ||
				text_len == 0) {
			continue;
		}
		int scope_idx = editorSyntaxFindInnermostScope(scopes, scope_count, definition_nodes[i]);
		if (scope_idx < 0) {
			continue;
		}
		if (!editorSyntaxScopeAddDefinition(&scopes[scope_idx], text, text_len)) {
			editorSyntaxScopeInfoFree(scopes, scope_count);
			goto oom;
		}
		if (!editorSyntaxLocalsContextMarkNode(ctx_out, definition_nodes[i], 1)) {
			editorSyntaxScopeInfoFree(scopes, scope_count);
			goto oom;
		}
	}

	for (int i = 0; i < reference_count; i++) {
		const char *text = NULL;
		size_t text_len = 0;
		if (!editorSyntaxNodeText(source, source_len, reference_nodes[i], &text, &text_len) ||
				text_len == 0) {
			continue;
		}
		int scope_idx = editorSyntaxFindInnermostScope(scopes, scope_count, reference_nodes[i]);
		if (scope_idx < 0) {
			continue;
		}

		int is_local = 0;
		int probe = scope_idx;
		while (probe >= 0) {
			if (editorSyntaxScopeHasDefinition(&scopes[probe], text, text_len)) {
				is_local = 1;
				break;
			}
			probe = scopes[probe].parent_idx;
		}
		if (!editorSyntaxLocalsContextMarkNode(ctx_out, reference_nodes[i], is_local)) {
			editorSyntaxScopeInfoFree(scopes, scope_count);
			goto oom;
		}
	}

	editorSyntaxScopeInfoFree(scopes, scope_count);
	ts_query_cursor_delete(cursor);
	free(scope_nodes);
	free(definition_nodes);
	free(reference_nodes);
	return 1;

oom:
	ts_query_cursor_delete(cursor);
	free(scope_nodes);
	free(definition_nodes);
	free(reference_nodes);
	editorSyntaxLocalsContextFree(ctx_out);
	return 0;
}

static int editorSyntaxMatchFindCaptureNode(const TSQueryMatch *match,
		uint32_t capture_id,
		TSNode *node_out) {
	if (match == NULL || node_out == NULL) {
		return 0;
	}
	for (uint16_t i = 0; i < match->capture_count; i++) {
		if (match->captures[i].index == capture_id) {
			*node_out = match->captures[i].node;
			return 1;
		}
	}
	return 0;
}

static int editorSyntaxPredicateArgText(const TSQuery *query,
		const TSQueryMatch *match,
		const struct editorSyntaxPredicateContext *ctx,
		const TSQueryPredicateStep *arg,
		const char **text_out,
		size_t *len_out) {
	if (query == NULL || match == NULL || ctx == NULL || arg == NULL ||
			text_out == NULL || len_out == NULL) {
		return 0;
	}

	if (arg->type == TSQueryPredicateStepTypeString) {
		uint32_t str_len = 0;
		const char *str = ts_query_string_value_for_id(query, arg->value_id, &str_len);
		if (str == NULL) {
			return 0;
		}
		*text_out = str;
		*len_out = (size_t)str_len;
		return 1;
	}

	if (arg->type == TSQueryPredicateStepTypeCapture) {
		TSNode node;
		if (!editorSyntaxMatchFindCaptureNode(match, arg->value_id, &node)) {
			return 0;
		}
		return editorSyntaxNodeText(ctx->source, ctx->source_len, node, text_out, len_out);
	}

	return 0;
}

static int editorSyntaxRegexMatch(const char *text, size_t text_len,
		const char *pattern, size_t pattern_len) {
	char *pattern_buf = malloc(pattern_len + 1);
	char *text_buf = malloc(text_len + 1);
	if (pattern_buf == NULL || text_buf == NULL) {
		free(pattern_buf);
		free(text_buf);
		return 0;
	}
	memcpy(pattern_buf, pattern, pattern_len);
	pattern_buf[pattern_len] = '\0';
	memcpy(text_buf, text, text_len);
	text_buf[text_len] = '\0';

	regex_t regex;
	int compiled = regcomp(&regex, pattern_buf, REG_EXTENDED | REG_NOSUB);
	free(pattern_buf);
	if (compiled != 0) {
		free(text_buf);
		return 0;
	}

	int matched = regexec(&regex, text_buf, 0, NULL, 0) == 0;
	regfree(&regex);
	free(text_buf);
	return matched;
}

static int editorSyntaxPredicateTargetNode(const TSQuery *query,
		const TSQueryMatch *match,
		const TSQueryPredicateStep *args,
		uint32_t arg_count,
		TSNode *node_out,
		const char **property_out,
		size_t *property_len_out) {
	if (query == NULL || match == NULL || args == NULL || arg_count == 0 ||
			node_out == NULL || property_out == NULL || property_len_out == NULL) {
		return 0;
	}

	if (args[0].type == TSQueryPredicateStepTypeCapture) {
		if (!editorSyntaxMatchFindCaptureNode(match, args[0].value_id, node_out)) {
			return 0;
		}
		if (arg_count < 2 || args[1].type != TSQueryPredicateStepTypeString) {
			return 0;
		}
		uint32_t property_len = 0;
		const char *property = ts_query_string_value_for_id(query, args[1].value_id,
				&property_len);
		if (property == NULL) {
			return 0;
		}
		*property_out = property;
		*property_len_out = property_len;
		return 1;
	}

	if (args[0].type == TSQueryPredicateStepTypeString && match->capture_count > 0) {
		*node_out = match->captures[0].node;
		uint32_t property_len = 0;
		const char *property = ts_query_string_value_for_id(query, args[0].value_id,
				&property_len);
		if (property == NULL) {
			return 0;
		}
		*property_out = property;
		*property_len_out = property_len;
		return 1;
	}

	return 0;
}

static int editorSyntaxEvaluatePredicate(const TSQuery *query,
		const TSQueryMatch *match,
		const struct editorSyntaxPredicateContext *ctx,
		const TSQueryPredicateStep *steps,
		uint32_t step_count) {
	if (query == NULL || match == NULL || ctx == NULL || steps == NULL || step_count == 0) {
		return 1;
	}
	if (steps[0].type != TSQueryPredicateStepTypeString) {
		return 1;
	}

	uint32_t command_len = 0;
	const char *command = ts_query_string_value_for_id(query, steps[0].value_id, &command_len);
	if (command == NULL) {
		return 1;
	}

	const TSQueryPredicateStep *args = &steps[1];
	uint32_t arg_count = step_count - 1;

	if (editorSyntaxStringEquals(command, command_len, "set!")) {
		return 1;
	}

	if (editorSyntaxStringEquals(command, command_len, "eq?") ||
			editorSyntaxStringEquals(command, command_len, "not-eq?")) {
		if (arg_count < 2) {
			return 1;
		}
		const char *left = NULL;
		size_t left_len = 0;
		const char *right = NULL;
		size_t right_len = 0;
		if (!editorSyntaxPredicateArgText(query, match, ctx, &args[0], &left, &left_len) ||
				!editorSyntaxPredicateArgText(query, match, ctx, &args[1], &right, &right_len)) {
			return 0;
		}
		int equal = (left_len == right_len) && memcmp(left, right, left_len) == 0;
		if (editorSyntaxStringEquals(command, command_len, "eq?")) {
			return equal;
		}
		return !equal;
	}

	if (editorSyntaxStringEquals(command, command_len, "match?") ||
			editorSyntaxStringEquals(command, command_len, "not-match?")) {
		if (arg_count < 2) {
			return 1;
		}
		const char *text = NULL;
		size_t text_len = 0;
		const char *pattern = NULL;
		size_t pattern_len = 0;
		if (!editorSyntaxPredicateArgText(query, match, ctx, &args[0], &text, &text_len) ||
				!editorSyntaxPredicateArgText(query, match, ctx, &args[1], &pattern,
						&pattern_len)) {
			return 0;
		}
		int matched = editorSyntaxRegexMatch(text, text_len, pattern, pattern_len);
		if (editorSyntaxStringEquals(command, command_len, "match?")) {
			return matched;
		}
		return !matched;
	}

	if (editorSyntaxStringEquals(command, command_len, "any-of?") ||
			editorSyntaxStringEquals(command, command_len, "not-any-of?")) {
		if (arg_count < 2) {
			return 1;
		}
		const char *target = NULL;
		size_t target_len = 0;
		if (!editorSyntaxPredicateArgText(query, match, ctx, &args[0], &target, &target_len)) {
			return 0;
		}

		int found = 0;
		for (uint32_t i = 1; i < arg_count; i++) {
			if (args[i].type != TSQueryPredicateStepTypeString) {
				continue;
			}
			uint32_t value_len = 0;
			const char *value = ts_query_string_value_for_id(query, args[i].value_id,
					&value_len);
			if (value == NULL) {
				continue;
			}
			if (target_len == value_len && memcmp(target, value, target_len) == 0) {
				found = 1;
				break;
			}
		}

		if (editorSyntaxStringEquals(command, command_len, "any-of?")) {
			return found;
		}
		return !found;
	}

	if (editorSyntaxStringEquals(command, command_len, "is?") ||
			editorSyntaxStringEquals(command, command_len, "is-not?")) {
		TSNode target;
		const char *property = NULL;
		size_t property_len = 0;
		if (!editorSyntaxPredicateTargetNode(query, match, args, arg_count, &target,
					&property, &property_len)) {
			return 1;
		}
		int is_property = 0;
		if (editorSyntaxStringEquals(property, property_len, "local")) {
			is_property = editorSyntaxLocalsContextNodeIsLocal(ctx->locals, target);
		}
		if (editorSyntaxStringEquals(command, command_len, "is?")) {
			return is_property;
		}
		return !is_property;
	}

	return 1;
}

static int editorSyntaxMatchPassesPredicates(const TSQuery *query,
		uint32_t pattern_index,
		const TSQueryMatch *match,
		const struct editorSyntaxPredicateContext *ctx) {
	if (query == NULL || match == NULL || ctx == NULL) {
		return 1;
	}

	uint32_t step_count = 0;
	const TSQueryPredicateStep *steps = ts_query_predicates_for_pattern(query, pattern_index,
			&step_count);
	if (steps == NULL || step_count == 0) {
		return 1;
	}

	uint32_t i = 0;
	while (i < step_count) {
		uint32_t start = i;
		while (i < step_count && steps[i].type != TSQueryPredicateStepTypeDone) {
			i++;
		}
		uint32_t end = i;
		if (end > start) {
			if (!editorSyntaxEvaluatePredicate(query, match, ctx, &steps[start], end - start)) {
				return 0;
			}
		}
		i++;
	}

	return 1;
}

static int editorSyntaxCaptureVecAppend(struct editorSyntaxCaptureVec *vec,
		uint32_t start_byte,
		uint32_t end_byte,
		enum editorSyntaxHighlightClass highlight_class) {
	if (vec == NULL) {
		return 0;
	}
	if (vec->count >= vec->cap) {
		int new_cap = vec->cap == 0 ? 128 : vec->cap * 2;
		if (new_cap <= vec->cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*vec->items);
		struct editorSyntaxCapture *grown = realloc(vec->items, bytes);
		if (grown == NULL) {
			return 0;
		}
		vec->items = grown;
		vec->cap = new_cap;
	}

	vec->items[vec->count].start_byte = start_byte;
	vec->items[vec->count].end_byte = end_byte;
	vec->items[vec->count].highlight_class = highlight_class;
	vec->count++;
	return 1;
}

static void editorSyntaxCaptureVecFree(struct editorSyntaxCaptureVec *vec) {
	if (vec == NULL) {
		return;
	}
	free(vec->items);
	vec->items = NULL;
	vec->count = 0;
	vec->cap = 0;
}

static int editorSyntaxCompareCapture(const void *a, const void *b) {
	const struct editorSyntaxCapture *left = a;
	const struct editorSyntaxCapture *right = b;
	if (left->start_byte < right->start_byte) {
		return -1;
	}
	if (left->start_byte > right->start_byte) {
		return 1;
	}
	if (left->end_byte < right->end_byte) {
		return -1;
	}
	if (left->end_byte > right->end_byte) {
		return 1;
	}
	return 0;
}

static int editorSyntaxCollectCapturesFromTree(const TSTree *tree,
		enum editorSyntaxLanguage language,
		const char *source,
		size_t source_len,
		uint32_t start_byte,
		uint32_t end_byte,
		struct editorSyntaxCaptureVec *captures_out) {
	if (captures_out == NULL) {
		return 0;
	}
	if (tree == NULL || start_byte >= end_byte) {
		return 1;
	}

	if (!editorSyntaxEnsureHighlightQuery(language)) {
		return 1;
	}
	const struct editorSyntaxQueryCacheEntry *cache =
			editorSyntaxHighlightQueryCacheForLanguage(language);
	if (cache == NULL || cache->query == NULL || cache->capture_classes == NULL) {
		return 1;
	}

	struct editorSyntaxLocalsContext locals;
	editorSyntaxLocalsContextInit(&locals);
	if (language == EDITOR_SYNTAX_JAVASCRIPT &&
			!editorSyntaxBuildLocalsContext(tree, language, source, source_len, &locals)) {
		return 0;
	}

	TSQueryCursor *cursor = ts_query_cursor_new();
	if (cursor == NULL) {
		editorSyntaxLocalsContextFree(&locals);
		return 0;
	}

	TSNode root = ts_tree_root_node(tree);
	ts_query_cursor_set_byte_range(cursor, start_byte, end_byte);
	ts_query_cursor_exec(cursor, cache->query, root);

	struct editorSyntaxPredicateContext predicate_ctx = {
		.source = source,
		.source_len = source_len,
		.locals = &locals
	};

	TSQueryMatch match;
	uint32_t capture_idx = 0;
	while (ts_query_cursor_next_capture(cursor, &match, &capture_idx)) {
		if (!editorSyntaxMatchPassesPredicates(cache->query, match.pattern_index, &match,
					&predicate_ctx)) {
			continue;
		}
		if (capture_idx >= match.capture_count) {
			continue;
		}
		TSQueryCapture capture = match.captures[capture_idx];
		if (capture.index >= cache->capture_count) {
			continue;
		}
		enum editorSyntaxHighlightClass highlight_class =
				cache->capture_classes[capture.index];
		if (highlight_class == EDITOR_SYNTAX_HL_NONE) {
			continue;
		}

		uint32_t capture_start = ts_node_start_byte(capture.node);
		uint32_t capture_end = ts_node_end_byte(capture.node);
		if (capture_end <= capture_start) {
			continue;
		}
		if (capture_end <= start_byte || capture_start >= end_byte) {
			continue;
		}
		if (capture_start < start_byte) {
			capture_start = start_byte;
		}
		if (capture_end > end_byte) {
			capture_end = end_byte;
		}
		if (capture_end <= capture_start) {
			continue;
		}

		if (!editorSyntaxCaptureVecAppend(captures_out, capture_start, capture_end,
					highlight_class)) {
			ts_query_cursor_delete(cursor);
			editorSyntaxLocalsContextFree(&locals);
			return 0;
		}
	}

	ts_query_cursor_delete(cursor);
	editorSyntaxLocalsContextFree(&locals);
	return 1;
}

static int editorSyntaxRangeVecAppend(struct editorSyntaxRangeVec *ranges, const TSRange *range) {
	if (ranges == NULL || range == NULL) {
		return 0;
	}
	if (ranges->count >= ranges->cap) {
		uint32_t new_cap = ranges->cap == 0 ? 16 : ranges->cap * 2;
		if (new_cap <= ranges->cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*ranges->items);
		TSRange *grown = realloc(ranges->items, bytes);
		if (grown == NULL) {
			return 0;
		}
		ranges->items = grown;
		ranges->cap = new_cap;
	}
	ranges->items[ranges->count] = *range;
	ranges->count++;
	return 1;
}

static void editorSyntaxRangeVecFree(struct editorSyntaxRangeVec *ranges) {
	if (ranges == NULL) {
		return;
	}
	free(ranges->items);
	ranges->items = NULL;
	ranges->count = 0;
	ranges->cap = 0;
}

static int editorSyntaxCompareRange(const void *a, const void *b) {
	const TSRange *left = a;
	const TSRange *right = b;
	if (left->start_byte < right->start_byte) {
		return -1;
	}
	if (left->start_byte > right->start_byte) {
		return 1;
	}
	if (left->end_byte < right->end_byte) {
		return -1;
	}
	if (left->end_byte > right->end_byte) {
		return 1;
	}
	return 0;
}

static enum editorSyntaxLanguage editorSyntaxLanguageFromInjectionName(const char *name,
		size_t len) {
	if (editorSyntaxStringEqualsNoCase(name, len, "javascript") ||
			editorSyntaxStringEqualsNoCase(name, len, "js")) {
		return EDITOR_SYNTAX_JAVASCRIPT;
	}
	if (editorSyntaxStringEqualsNoCase(name, len, "css")) {
		return EDITOR_SYNTAX_CSS;
	}
	return EDITOR_SYNTAX_NONE;
}

static int editorSyntaxCollectHtmlInjectionRanges(const struct editorSyntaxState *state,
		const char *source,
		size_t source_len,
		struct editorSyntaxRangeVec *javascript_ranges,
		struct editorSyntaxRangeVec *css_ranges) {
	if (state == NULL || source == NULL || javascript_ranges == NULL || css_ranges == NULL) {
		return 0;
	}
	if (state->host.tree == NULL) {
		return 1;
	}
	if (!editorSyntaxEnsureHtmlInjectionQuery()) {
		return 1;
	}

	const struct editorSyntaxQueryCacheEntry *cache = &g_html_injection_query_cache;
	if (cache->query == NULL || cache->capture_roles == NULL ||
			cache->pattern_injection_languages == NULL) {
		return 1;
	}

	TSQueryCursor *cursor = ts_query_cursor_new();
	if (cursor == NULL) {
		return 0;
	}

	TSNode root = ts_tree_root_node(state->host.tree);
	ts_query_cursor_exec(cursor, cache->query, root);

	struct editorSyntaxPredicateContext predicate_ctx = {
		.source = source,
		.source_len = source_len,
		.locals = NULL
	};

	TSQueryMatch match;
	while (ts_query_cursor_next_match(cursor, &match)) {
		if (match.pattern_index >= cache->pattern_count) {
			continue;
		}
		if (!editorSyntaxMatchPassesPredicates(cache->query, match.pattern_index, &match,
					&predicate_ctx)) {
			continue;
		}

		const char *lang_name = cache->pattern_injection_languages[match.pattern_index];
		if (lang_name == NULL) {
			continue;
		}
		enum editorSyntaxLanguage target_lang =
				editorSyntaxLanguageFromInjectionName(lang_name, strlen(lang_name));
		if (target_lang != EDITOR_SYNTAX_JAVASCRIPT && target_lang != EDITOR_SYNTAX_CSS) {
			continue;
		}

		for (uint16_t capture_idx = 0; capture_idx < match.capture_count; capture_idx++) {
			TSQueryCapture capture = match.captures[capture_idx];
			if (capture.index >= cache->capture_count) {
				continue;
			}
			if (cache->capture_roles[capture.index] !=
					EDITOR_SYNTAX_CAPTURE_ROLE_INJECTION_CONTENT) {
				continue;
			}

			TSRange range = {
				.start_point = ts_node_start_point(capture.node),
				.end_point = ts_node_end_point(capture.node),
				.start_byte = ts_node_start_byte(capture.node),
				.end_byte = ts_node_end_byte(capture.node)
			};
			if (range.end_byte <= range.start_byte) {
				continue;
			}

			int ok = 0;
			if (target_lang == EDITOR_SYNTAX_JAVASCRIPT) {
				ok = editorSyntaxRangeVecAppend(javascript_ranges, &range);
			} else {
				ok = editorSyntaxRangeVecAppend(css_ranges, &range);
			}
			if (!ok) {
				ts_query_cursor_delete(cursor);
				return 0;
			}
		}
	}

	ts_query_cursor_delete(cursor);
	if (javascript_ranges->count > 1) {
		qsort(javascript_ranges->items, javascript_ranges->count,
				sizeof(javascript_ranges->items[0]), editorSyntaxCompareRange);
	}
	if (css_ranges->count > 1) {
		qsort(css_ranges->items, css_ranges->count,
				sizeof(css_ranges->items[0]), editorSyntaxCompareRange);
	}
	return 1;
}

static void editorSyntaxApplyInputEdit(TSTree *tree, const struct editorSyntaxEdit *edit) {
	if (tree == NULL || edit == NULL) {
		return;
	}
	TSInputEdit ts_edit = {
		.start_byte = edit->start_byte,
		.old_end_byte = edit->old_end_byte,
		.new_end_byte = edit->new_end_byte,
		.start_point = {.row = edit->start_point.row, .column = edit->start_point.column},
		.old_end_point = {.row = edit->old_end_point.row, .column = edit->old_end_point.column},
		.new_end_point = {.row = edit->new_end_point.row, .column = edit->new_end_point.column}
	};
	ts_tree_edit(tree, &ts_edit);
}

static int editorSyntaxStateParseHtmlInjections(struct editorSyntaxState *state,
		const char *source,
		size_t len,
		const struct editorSyntaxEdit *incremental_edit) {
	if (state == NULL || source == NULL) {
		return 0;
	}
	if (state->language != EDITOR_SYNTAX_HTML) {
		return 1;
	}

	struct editorSyntaxRangeVec javascript_ranges = {0};
	struct editorSyntaxRangeVec css_ranges = {0};
	if (!editorSyntaxCollectHtmlInjectionRanges(state, source, len, &javascript_ranges,
				&css_ranges)) {
		editorSyntaxRangeVecFree(&javascript_ranges);
		editorSyntaxRangeVecFree(&css_ranges);
		return 0;
	}

	if (incremental_edit != NULL) {
		editorSyntaxApplyInputEdit(state->javascript_injection.tree, incremental_edit);
		editorSyntaxApplyInputEdit(state->css_injection.tree, incremental_edit);
	}

	if (!editorSyntaxParsedTreeSetIncludedRanges(&state->javascript_injection,
			javascript_ranges.items, javascript_ranges.count) ||
			!editorSyntaxParsedTreeSetIncludedRanges(&state->css_injection,
					css_ranges.items, css_ranges.count)) {
		editorSyntaxRangeVecFree(&javascript_ranges);
		editorSyntaxRangeVecFree(&css_ranges);
		return 0;
	}

	int incremental = incremental_edit != NULL;
	int ok = editorSyntaxParsedTreeParse(&state->javascript_injection, source, len, incremental) &&
			editorSyntaxParsedTreeParse(&state->css_injection, source, len, incremental);

	editorSyntaxRangeVecFree(&javascript_ranges);
	editorSyntaxRangeVecFree(&css_ranges);
	return ok;
}

static int editorSyntaxStateUpdateSourceSnapshot(struct editorSyntaxState *state,
		const char *source,
		size_t len) {
	if (state == NULL || source == NULL) {
		return 0;
	}
	char *dup = malloc(len + 1);
	if (dup == NULL) {
		return 0;
	}
	if (len > 0) {
		memcpy(dup, source, len);
	}
	dup[len] = '\0';
	free(state->source_snapshot);
	state->source_snapshot = dup;
	state->source_snapshot_len = len;
	return 1;
}

struct editorSyntaxState *editorSyntaxStateCreate(enum editorSyntaxLanguage language) {
	const TSLanguage *host_language = editorSyntaxLanguageObject(language);
	if (host_language == NULL) {
		return NULL;
	}
	(void)host_language;

	struct editorSyntaxState *state = malloc(sizeof(*state));
	if (state == NULL) {
		return NULL;
	}
	state->language = language;
	editorSyntaxParsedTreeInit(&state->host, language);
	editorSyntaxParsedTreeInit(&state->javascript_injection, EDITOR_SYNTAX_JAVASCRIPT);
	editorSyntaxParsedTreeInit(&state->css_injection, EDITOR_SYNTAX_CSS);
	state->source_snapshot = NULL;
	state->source_snapshot_len = 0;

	if (!editorSyntaxParsedTreeCreateParser(&state->host, language)) {
		free(state);
		return NULL;
	}

	if (language == EDITOR_SYNTAX_HTML) {
		if (!editorSyntaxParsedTreeCreateParser(&state->javascript_injection,
					EDITOR_SYNTAX_JAVASCRIPT) ||
				!editorSyntaxParsedTreeCreateParser(&state->css_injection,
						EDITOR_SYNTAX_CSS)) {
			editorSyntaxParsedTreeDestroy(&state->host);
			editorSyntaxParsedTreeDestroy(&state->javascript_injection);
			editorSyntaxParsedTreeDestroy(&state->css_injection);
			free(state->source_snapshot);
			free(state);
			return NULL;
		}
	}

	return state;
}

void editorSyntaxStateDestroy(struct editorSyntaxState *state) {
	if (state == NULL) {
		return;
	}
	editorSyntaxParsedTreeDestroy(&state->host);
	editorSyntaxParsedTreeDestroy(&state->javascript_injection);
	editorSyntaxParsedTreeDestroy(&state->css_injection);
	free(state->source_snapshot);
	state->source_snapshot = NULL;
	state->source_snapshot_len = 0;
	free(state);
}

int editorSyntaxStateParseFull(struct editorSyntaxState *state, const char *source, size_t len) {
	if (state == NULL || source == NULL || !editorSyntaxLengthFitsTreeSitter(len)) {
		return 0;
	}

	if (!editorSyntaxParsedTreeParse(&state->host, source, len, 0)) {
		return 0;
	}
	if (!editorSyntaxStateParseHtmlInjections(state, source, len, NULL)) {
		return 0;
	}
	if (!editorSyntaxStateUpdateSourceSnapshot(state, source, len)) {
		return 0;
	}
	return 1;
}

int editorSyntaxStateApplyEditAndParse(struct editorSyntaxState *state,
		const struct editorSyntaxEdit *edit,
		const char *source,
		size_t len) {
	if (state == NULL || edit == NULL || source == NULL || !editorSyntaxLengthFitsTreeSitter(len) ||
			state->host.parser == NULL || state->host.tree == NULL) {
		return 0;
	}

	editorSyntaxApplyInputEdit(state->host.tree, edit);
	if (!editorSyntaxParsedTreeParse(&state->host, source, len, 1)) {
		return 0;
	}
	if (!editorSyntaxStateParseHtmlInjections(state, source, len, edit)) {
		return 0;
	}
	if (!editorSyntaxStateUpdateSourceSnapshot(state, source, len)) {
		return 0;
	}
	return 1;
}

int editorSyntaxStateHasTree(const struct editorSyntaxState *state) {
	return state != NULL && state->host.tree != NULL;
}

const char *editorSyntaxStateRootType(const struct editorSyntaxState *state) {
	if (state == NULL || state->host.tree == NULL) {
		return NULL;
	}
	TSNode root = ts_tree_root_node(state->host.tree);
	return ts_node_type(root);
}

enum editorSyntaxLanguage editorSyntaxStateLanguage(const struct editorSyntaxState *state) {
	if (state == NULL) {
		return EDITOR_SYNTAX_NONE;
	}
	return state->language;
}

int editorSyntaxStateCollectCapturesForRange(const struct editorSyntaxState *state,
		uint32_t start_byte,
		uint32_t end_byte,
		struct editorSyntaxCapture *captures,
		int max_captures,
		int *count_out) {
	if (count_out != NULL) {
		*count_out = 0;
	}
	if (state == NULL || start_byte >= end_byte || max_captures < 0 ||
			(max_captures > 0 && captures == NULL)) {
		return 0;
	}
	if (max_captures == 0 || state->host.tree == NULL) {
		return 1;
	}

	struct editorSyntaxCaptureVec collected = {0};
	const char *source = state->source_snapshot != NULL ? state->source_snapshot : "";
	size_t source_len = state->source_snapshot != NULL ? state->source_snapshot_len : 0;
	int ok = editorSyntaxCollectCapturesFromTree(state->host.tree, state->language,
			source, source_len, start_byte, end_byte, &collected);
	if (!ok) {
		editorSyntaxCaptureVecFree(&collected);
		return 0;
	}

	if (state->language == EDITOR_SYNTAX_HTML) {
		if (!editorSyntaxCollectCapturesFromTree(state->javascript_injection.tree,
					EDITOR_SYNTAX_JAVASCRIPT,
					source, source_len, start_byte, end_byte, &collected) ||
				!editorSyntaxCollectCapturesFromTree(state->css_injection.tree,
						EDITOR_SYNTAX_CSS,
						source, source_len, start_byte, end_byte, &collected)) {
			editorSyntaxCaptureVecFree(&collected);
			return 0;
		}
	}

	if (state->language == EDITOR_SYNTAX_HTML && collected.count > 1) {
		qsort(collected.items, (size_t)collected.count, sizeof(collected.items[0]),
				editorSyntaxCompareCapture);
	}

	int out_count = collected.count;
	if (out_count > max_captures) {
		out_count = max_captures;
	}
	for (int i = 0; i < out_count; i++) {
		captures[i] = collected.items[i];
	}
	if (count_out != NULL) {
		*count_out = out_count;
	}

	editorSyntaxCaptureVecFree(&collected);
	return 1;
}

void editorSyntaxReleaseSharedResources(void) {
	editorSyntaxClearQueryCacheEntry(&g_c_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_shell_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_html_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_javascript_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_css_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_javascript_locals_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_html_injection_query_cache);
}
