#!/usr/bin/env bash
# Generate src/config/default_config_data.h from config.toml.example.
# Output is a header containing one byte array of the file contents.
# Read by src/config/common.c.
set -euo pipefail

if [[ $# -ne 2 ]]; then
	echo "usage: $0 <input> <output-header>" >&2
	exit 2
fi

input="$1"
out="$2"
tmp="${out}.tmp"

if [[ ! -f "$input" ]]; then
	echo "missing input file: $input" >&2
	exit 1
fi

{
	printf '/* GENERATED by scripts/embed_default_config.sh - do not edit. */\n'
	printf '#ifndef ROTIDE_DEFAULT_CONFIG_DATA_H\n'
	printf '#define ROTIDE_DEFAULT_CONFIG_DATA_H\n\n'
	printf 'static const unsigned char EDITOR_CONFIG_DEFAULT_GLOBAL_CONTENT[] = {'
	od -An -vtx1 "$input" | awk '{ for (i=1; i<=NF; i++) printf "0x%s,", $i }'
	printf '};\n'
	printf '#define EDITOR_CONFIG_DEFAULT_GLOBAL_CONTENT_SIZE (sizeof(EDITOR_CONFIG_DEFAULT_GLOBAL_CONTENT))\n'
	printf '\n#endif\n'
} > "$tmp"
mv "$tmp" "$out"
