#!/usr/bin/env bash
# Generate src/language/syntax_query_data.h from scripts/queries_manifest.txt.
# Output is a header containing one byte array per input file plus a parts
# table per manifest symbol. Read by syntax_queries.c.
set -euo pipefail

if [[ $# -ne 2 ]]; then
	echo "usage: $0 <manifest> <output-header>" >&2
	exit 2
fi

manifest="$1"
out="$2"
tmp="${out}.tmp"

emit_byte_array() {
	local sym="$1"
	local file="$2"
	printf 'static const unsigned char %s[] = {' "$sym"
	od -An -vtx1 "$file" | awk '{ for (i=1; i<=NF; i++) printf "0x%s,", $i }'
	printf '};\n'
}

{
	printf '/* GENERATED by scripts/embed_queries.sh - do not edit. */\n'
	printf '#ifndef ROTIDE_SYNTAX_QUERY_DATA_H\n'
	printf '#define ROTIDE_SYNTAX_QUERY_DATA_H\n\n'
	printf '#include "language/languages.h"\n\n'

	while IFS= read -r line || [[ -n "$line" ]]; do
		line="${line%%#*}"
		# trim
		line="${line#"${line%%[![:space:]]*}"}"
		line="${line%"${line##*[![:space:]]}"}"
		[[ -z "$line" ]] && continue

		read -r -a fields <<< "$line"
		sym="${fields[0]}"
		files=("${fields[@]:1}")

		if [[ ${#files[@]} -eq 0 ]]; then
			echo "manifest entry '$sym' has no input files" >&2
			exit 1
		fi

		idx=0
		for f in "${files[@]}"; do
			if [[ ! -f "$f" ]]; then
				echo "missing input file for '$sym': $f" >&2
				exit 1
			fi
			emit_byte_array "editor_query_${sym}_part${idx}" "$f"
			idx=$((idx + 1))
		done

		printf 'static const struct editorSyntaxEmbeddedQueryPart editor_query_%s_parts[] = {\n' "$sym"
		idx=0
		for f in "${files[@]}"; do
			printf '\t{ editor_query_%s_part%d, sizeof(editor_query_%s_part%d) },\n' \
				"$sym" "$idx" "$sym" "$idx"
			idx=$((idx + 1))
		done
		printf '};\n'
		printf '#define EDITOR_QUERY_%s_PART_COUNT %d\n\n' \
			"$(printf '%s' "$sym" | tr '[:lower:]' '[:upper:]')" "${#files[@]}"
	done < "$manifest"

	printf '#endif\n'
} > "$tmp"
mv "$tmp" "$out"
