#include "language/syntax.h"

#include <ctype.h>
#include <limits.h>
#include <regex.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <time.h>

#include "tree_sitter/api.h"

// Generated by vendored tree-sitter grammar sources.
extern const TSLanguage *tree_sitter_c(void);
extern const TSLanguage *tree_sitter_cpp(void);
extern const TSLanguage *tree_sitter_go(void);
extern const TSLanguage *tree_sitter_bash(void);
extern const TSLanguage *tree_sitter_html(void);
extern const TSLanguage *tree_sitter_javascript(void);
extern const TSLanguage *tree_sitter_css(void);

#include "language/syntax_queries.c"

static int editorSyntaxIsShellInterpreterName(const char *token, size_t len) {
	return (len == 2 && strncasecmp(token, "sh", 2) == 0) ||
			(len == 4 && strncasecmp(token, "bash", 4) == 0) ||
			(len == 3 && strncasecmp(token, "zsh", 3) == 0) ||
			(len == 3 && strncasecmp(token, "ksh", 3) == 0);
}

static int editorSyntaxTokenFromLine(const char *line, size_t line_len, size_t *idx,
		const char **token_out, size_t *token_len_out) {
	if (line == NULL || idx == NULL || token_out == NULL || token_len_out == NULL) {
		return 0;
	}

	size_t i = *idx;
	while (i < line_len && isspace((unsigned char)line[i])) {
		i++;
	}
	if (i >= line_len) {
		*idx = i;
		return 0;
	}

	size_t start = i;
	while (i < line_len && !isspace((unsigned char)line[i])) {
		i++;
	}

	*idx = i;
	*token_out = &line[start];
	*token_len_out = i - start;
	return 1;
}

static enum editorSyntaxLanguage editorSyntaxDetectLanguageFromShebang(const char *first_line) {
	if (first_line == NULL || first_line[0] != '#' || first_line[1] != '!') {
		return EDITOR_SYNTAX_NONE;
	}

	size_t line_len = strlen(first_line);
	size_t idx = 2;
	const char *token = NULL;
	size_t token_len = 0;
	if (!editorSyntaxTokenFromLine(first_line, line_len, &idx, &token, &token_len)) {
		return EDITOR_SYNTAX_NONE;
	}

	const char *base = token;
	for (size_t i = 0; i < token_len; i++) {
		if (token[i] == '/') {
			base = &token[i + 1];
		}
	}
	size_t base_len = token_len - (size_t)(base - token);

	if (editorSyntaxIsShellInterpreterName(base, base_len)) {
		return EDITOR_SYNTAX_SHELL;
	}

	if (base_len == 3 && strncasecmp(base, "env", 3) == 0) {
		for (;;) {
			if (!editorSyntaxTokenFromLine(first_line, line_len, &idx, &token, &token_len)) {
				break;
			}
			if (token_len > 0 && token[0] == '-') {
				continue;
			}

			base = token;
			for (size_t i = 0; i < token_len; i++) {
				if (token[i] == '/') {
					base = &token[i + 1];
				}
			}
			base_len = token_len - (size_t)(base - token);
			if (editorSyntaxIsShellInterpreterName(base, base_len)) {
				return EDITOR_SYNTAX_SHELL;
			}
			break;
		}
	}

	return EDITOR_SYNTAX_NONE;
}

static int editorSyntaxFilenameIsExtensionless(const char *filename) {
	if (filename == NULL || filename[0] == '\0') {
		return 1;
	}

	const char *base = strrchr(filename, '/');
	if (base != NULL) {
		base++;
	} else {
		base = filename;
	}
	if (base[0] == '\0') {
		return 0;
	}
	if (strchr(base, '.') == NULL) {
		return 1;
	}
	if (base[0] == '.' && strchr(base + 1, '.') == NULL) {
		return 1;
	}
	return 0;
}

enum editorSyntaxLanguage editorSyntaxDetectLanguageFromFilename(const char *filename) {
	if (filename == NULL || filename[0] == '\0') {
		return EDITOR_SYNTAX_NONE;
	}

	const char *dot = strrchr(filename, '.');
	if (dot != NULL && (strcmp(dot, ".c") == 0 || strcmp(dot, ".h") == 0)) {
		return EDITOR_SYNTAX_C;
	}
	if (dot != NULL &&
			(strcmp(dot, ".cc") == 0 || strcmp(dot, ".cpp") == 0 ||
					strcmp(dot, ".cxx") == 0 || strcmp(dot, ".c++") == 0 ||
					strcmp(dot, ".hh") == 0 || strcmp(dot, ".hpp") == 0 ||
					strcmp(dot, ".hxx") == 0)) {
		return EDITOR_SYNTAX_CPP;
	}
	if (dot != NULL && strcmp(dot, ".go") == 0) {
		return EDITOR_SYNTAX_GO;
	}
	if (dot != NULL &&
			(strcmp(dot, ".sh") == 0 || strcmp(dot, ".bash") == 0 ||
					strcmp(dot, ".zsh") == 0 || strcmp(dot, ".ksh") == 0)) {
		return EDITOR_SYNTAX_SHELL;
	}
	if (dot != NULL &&
			(strcmp(dot, ".html") == 0 || strcmp(dot, ".htm") == 0 ||
					strcmp(dot, ".xhtml") == 0)) {
		return EDITOR_SYNTAX_HTML;
	}
	if (dot != NULL &&
			(strcmp(dot, ".js") == 0 || strcmp(dot, ".mjs") == 0 ||
					strcmp(dot, ".cjs") == 0 || strcmp(dot, ".jsx") == 0)) {
		return EDITOR_SYNTAX_JAVASCRIPT;
	}
	if (dot != NULL && (strcmp(dot, ".css") == 0 || strcmp(dot, ".scss") == 0)) {
		return EDITOR_SYNTAX_CSS;
	}

	const char *base = strrchr(filename, '/');
	if (base != NULL) {
		base++;
	} else {
		base = filename;
	}
	if (strcmp(base, ".bashrc") == 0 || strcmp(base, ".zshrc") == 0 ||
			strcmp(base, ".profile") == 0 || strcmp(base, ".bash_profile") == 0 ||
			strcmp(base, ".bash_login") == 0 || strcmp(base, ".kshrc") == 0) {
		return EDITOR_SYNTAX_SHELL;
	}
	if (strcmp(base, "go.mod") == 0 || strcmp(base, "go.sum") == 0) {
		return EDITOR_SYNTAX_GO;
	}

	return EDITOR_SYNTAX_NONE;
}

enum editorSyntaxLanguage editorSyntaxDetectLanguageFromFilenameAndFirstLine(
		const char *filename, const char *first_line) {
	enum editorSyntaxLanguage from_filename = editorSyntaxDetectLanguageFromFilename(filename);
	if (from_filename != EDITOR_SYNTAX_NONE) {
		return from_filename;
	}
	if (!editorSyntaxFilenameIsExtensionless(filename)) {
		return EDITOR_SYNTAX_NONE;
	}

	return editorSyntaxDetectLanguageFromShebang(first_line);
}

static void editorSyntaxParsedTreeInit(struct editorSyntaxParsedTree *parsed,
		enum editorSyntaxLanguage language) {
	if (parsed == NULL) {
		return;
	}
	parsed->language = language;
	parsed->parser = NULL;
	parsed->tree = NULL;
	parsed->included_ranges = NULL;
	parsed->included_range_count = 0;
	parsed->revision = 0;
}

static int editorSyntaxParsedTreeCreateParser(struct editorSyntaxParsedTree *parsed,
		enum editorSyntaxLanguage language) {
	if (parsed == NULL) {
		return 0;
	}
	const TSLanguage *ts_language = editorSyntaxLanguageObject(language);
	if (ts_language == NULL) {
		return 0;
	}

	parsed->language = language;
	parsed->parser = ts_parser_new();
	if (parsed->parser == NULL) {
		return 0;
	}
	if (!ts_parser_set_language(parsed->parser, ts_language)) {
		ts_parser_delete(parsed->parser);
		parsed->parser = NULL;
		return 0;
	}
	return 1;
}

static void editorSyntaxParsedTreeDestroy(struct editorSyntaxParsedTree *parsed) {
	if (parsed == NULL) {
		return;
	}
	if (parsed->tree != NULL) {
		ts_tree_delete(parsed->tree);
		parsed->tree = NULL;
	}
	if (parsed->parser != NULL) {
		ts_parser_delete(parsed->parser);
		parsed->parser = NULL;
	}
	free(parsed->included_ranges);
	parsed->included_ranges = NULL;
	parsed->included_range_count = 0;
}

static void editorSyntaxParsedTreeResetTree(struct editorSyntaxParsedTree *parsed) {
	if (parsed == NULL || parsed->tree == NULL) {
		return;
	}
	ts_tree_delete(parsed->tree);
	parsed->tree = NULL;
	parsed->revision++;
}

static void editorSyntaxStateClearChangedRanges(struct editorSyntaxState *state) {
	if (state == NULL) {
		return;
	}
	state->last_changed_range_count = 0;
}

static int editorSyntaxStateEnsureChangedRangeCapacity(struct editorSyntaxState *state, int needed) {
	if (state == NULL || needed < 0) {
		return 0;
	}
	if (needed <= state->last_changed_range_cap) {
		return 1;
	}

	int new_cap = state->last_changed_range_cap == 0 ? 16 : state->last_changed_range_cap;
	while (new_cap < needed) {
		if (new_cap > INT_MAX / 2) {
			return 0;
		}
		new_cap *= 2;
	}
	size_t bytes = (size_t)new_cap * sizeof(*state->last_changed_ranges);
	struct editorSyntaxByteRange *grown = realloc(state->last_changed_ranges, bytes);
	if (grown == NULL) {
		return 0;
	}
	state->last_changed_ranges = grown;
	state->last_changed_range_cap = new_cap;
	return 1;
}

static int editorSyntaxStateAppendChangedRange(struct editorSyntaxState *state,
		uint32_t start_byte, uint32_t end_byte) {
	if (state == NULL || end_byte <= start_byte) {
		return 1;
	}

	if (state->last_changed_range_count > 0) {
		struct editorSyntaxByteRange *last =
				&state->last_changed_ranges[state->last_changed_range_count - 1];
		if (start_byte <= last->end_byte) {
			if (end_byte > last->end_byte) {
				last->end_byte = end_byte;
			}
			return 1;
		}
	}

	if (!editorSyntaxStateEnsureChangedRangeCapacity(state, state->last_changed_range_count + 1)) {
		return 0;
	}
	state->last_changed_ranges[state->last_changed_range_count].start_byte = start_byte;
	state->last_changed_ranges[state->last_changed_range_count].end_byte = end_byte;
	state->last_changed_range_count++;
	return 1;
}

static int editorSyntaxStateSetChangedRangesFull(struct editorSyntaxState *state, size_t source_len) {
	if (state == NULL) {
		return 0;
	}
	editorSyntaxStateClearChangedRanges(state);
	if (source_len == 0) {
		return 1;
	}
	if (source_len > UINT32_MAX) {
		source_len = UINT32_MAX;
	}
	return editorSyntaxStateAppendChangedRange(state, 0, (uint32_t)source_len);
}

static int editorSyntaxStateSetChangedRangesFromTrees(struct editorSyntaxState *state,
		const TSTree *old_tree,
		const TSTree *new_tree) {
	if (state == NULL) {
		return 0;
	}
	editorSyntaxStateClearChangedRanges(state);
	if (old_tree == NULL || new_tree == NULL) {
		return 1;
	}

	uint32_t range_count = 0;
	TSRange *ranges = ts_tree_get_changed_ranges(old_tree, new_tree, &range_count);
	if (ranges == NULL && range_count > 0) {
		return 0;
	}

	int ok = 1;
	for (uint32_t i = 0; i < range_count; i++) {
		if (!editorSyntaxStateAppendChangedRange(state, ranges[i].start_byte,
					ranges[i].end_byte)) {
			ok = 0;
			break;
		}
	}
	free(ranges);
	return ok;
}

static int editorSyntaxParsedTreeSetIncludedRanges(struct editorSyntaxParsedTree *parsed,
		const TSRange *ranges,
		uint32_t range_count) {
	if (parsed == NULL || parsed->parser == NULL) {
		return 0;
	}

	TSRange *owned = NULL;
	if (range_count > 0) {
		size_t bytes = (size_t)range_count * sizeof(*owned);
		owned = malloc(bytes);
		if (owned == NULL) {
			return 0;
		}
		memcpy(owned, ranges, bytes);
	}

	if (!ts_parser_set_included_ranges(parsed->parser, owned, range_count)) {
		free(owned);
		return 0;
	}

	free(parsed->included_ranges);
	parsed->included_ranges = owned;
	parsed->included_range_count = range_count;
	return 1;
}

static int editorSyntaxParsedTreeParse(struct editorSyntaxParsedTree *parsed,
		struct editorSyntaxState *state,
		const struct editorTextSource *source,
		int incremental) {
	if (parsed == NULL || parsed->parser == NULL || source == NULL || source->read == NULL ||
			!editorSyntaxLengthFitsTreeSitter(source->length)) {
		return 0;
	}

	TSTree *old_tree = incremental ? parsed->tree : NULL;
	struct editorSyntaxBudgetConfig budget =
			editorSyntaxBudgetConfigForMode(state != NULL ? state->perf_mode :
					EDITOR_SYNTAX_PERF_NORMAL);
	TSInput input = {
		.payload = (void *)source,
		.read = editorSyntaxSourceRead,
		.encoding = TSInputEncodingUTF8,
		.decode = NULL
	};

	TSTree *new_tree = NULL;
	if (budget.parse_budget_ns > 0) {
		struct editorSyntaxDeadlineContext parse_deadline = {0};
		parse_deadline.deadline_ns = editorSyntaxComputeDeadlineNs(budget.parse_budget_ns);
		TSParseOptions options = {
			.payload = &parse_deadline,
			.progress_callback = editorSyntaxParseProgressCallback
		};
		new_tree = ts_parser_parse_with_options(parsed->parser, old_tree, input, options);
		if (new_tree == NULL && parse_deadline.exceeded) {
			if (old_tree == NULL &&
					source->length <= ROTIDE_SYNTAX_PERF_DEGRADED_PREDICATES_BYTES) {
				new_tree = ts_parser_parse(parsed->parser, old_tree, input);
			}
			if (new_tree == NULL) {
				if (state != NULL) {
					state->budget_parse_exceeded = 1;
				}
				return 1;
			}
		}
	} else {
		new_tree = ts_parser_parse(parsed->parser, old_tree, input);
	}
	if (new_tree == NULL) {
		return 0;
	}

	if (state != NULL) {
		if (!editorSyntaxStateSetChangedRangesFromTrees(state, old_tree, new_tree)) {
			ts_tree_delete(new_tree);
			return 0;
		}
	}

	if (parsed->tree != NULL) {
		ts_tree_delete(parsed->tree);
	}
	parsed->tree = new_tree;
	parsed->revision++;
	return 1;
}

static int editorSyntaxNodeContains(TSNode outer, TSNode inner) {
	uint32_t outer_start = ts_node_start_byte(outer);
	uint32_t outer_end = ts_node_end_byte(outer);
	uint32_t inner_start = ts_node_start_byte(inner);
	uint32_t inner_end = ts_node_end_byte(inner);
	return outer_start <= inner_start && outer_end >= inner_end;
}

static uint32_t editorSyntaxNodeSpan(TSNode node) {
	uint32_t start = ts_node_start_byte(node);
	uint32_t end = ts_node_end_byte(node);
	if (end < start) {
		return 0;
	}
	return end - start;
}

static int editorSyntaxStateCopySourceRangeToScratch(struct editorSyntaxState *state,
		const struct editorTextSource *source,
		size_t start_byte,
		size_t end_byte,
		int scratch_idx,
		const char **text_out, size_t *len_out) {
	if (state == NULL || source == NULL || text_out == NULL || len_out == NULL ||
			end_byte < start_byte || end_byte > source->length) {
		return 0;
	}
	if (start_byte == end_byte) {
		*text_out = "";
		*len_out = 0;
		return 1;
	}

	char **scratch = scratch_idx == 0 ? &state->scratch_primary : &state->scratch_secondary;
	size_t *scratch_cap = scratch_idx == 0 ?
			&state->scratch_primary_cap : &state->scratch_secondary_cap;
	size_t len = end_byte - start_byte;
	if (*scratch_cap < len + 1) {
		char *grown = realloc(*scratch, len + 1);
		if (grown == NULL) {
			return 0;
		}
		*scratch = grown;
		*scratch_cap = len + 1;
	}
	if (!editorTextSourceCopyRange(source, start_byte, end_byte, *scratch)) {
		return 0;
	}
	(*scratch)[len] = '\0';
	*text_out = *scratch;
	*len_out = len;
	return 1;
}

static int editorSyntaxNodeText(struct editorSyntaxState *state,
		const struct editorTextSource *source, TSNode node, int scratch_idx,
		const char **text_out, size_t *len_out) {
	if (source == NULL || text_out == NULL || len_out == NULL) {
		return 0;
	}

	uint32_t start = ts_node_start_byte(node);
	uint32_t end = ts_node_end_byte(node);
	if (end < start) {
		return 0;
	}
	return editorSyntaxStateCopySourceRangeToScratch(state, source, start, end, scratch_idx,
			text_out, len_out);
}

static int editorSyntaxNodeArrayAppend(TSNode **items, int *count, int *cap, TSNode node) {
	if (items == NULL || count == NULL || cap == NULL) {
		return 0;
	}
	if (*count >= *cap) {
		int new_cap = *cap == 0 ? 16 : *cap * 2;
		if (new_cap <= *cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(**items);
		TSNode *grown = realloc(*items, bytes);
		if (grown == NULL) {
			return 0;
		}
		*items = grown;
		*cap = new_cap;
	}
	(*items)[*count] = node;
	(*count)++;
	return 1;
}

static void editorSyntaxLocalsContextInit(struct editorSyntaxLocalsContext *ctx) {
	if (ctx == NULL) {
		return;
	}
	ctx->marks = NULL;
	ctx->count = 0;
	ctx->cap = 0;
}

static void editorSyntaxLocalsContextFree(struct editorSyntaxLocalsContext *ctx) {
	if (ctx == NULL) {
		return;
	}
	free(ctx->marks);
	ctx->marks = NULL;
	ctx->count = 0;
	ctx->cap = 0;
}

static int editorSyntaxLocalsContextMarkNode(struct editorSyntaxLocalsContext *ctx,
		TSNode node,
		int is_local) {
	if (ctx == NULL) {
		return 0;
	}
	for (int i = 0; i < ctx->count; i++) {
		if (ts_node_eq(ctx->marks[i].node, node)) {
			if (is_local) {
				ctx->marks[i].is_local = 1;
			}
			return 1;
		}
	}

	if (ctx->count >= ctx->cap) {
		int new_cap = ctx->cap == 0 ? 32 : ctx->cap * 2;
		if (new_cap <= ctx->cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*ctx->marks);
		struct editorSyntaxLocalMark *grown = realloc(ctx->marks, bytes);
		if (grown == NULL) {
			return 0;
		}
		ctx->marks = grown;
		ctx->cap = new_cap;
	}

	ctx->marks[ctx->count].node = node;
	ctx->marks[ctx->count].is_local = is_local ? 1 : 0;
	ctx->count++;
	return 1;
}

static int editorSyntaxLocalsContextNodeIsLocal(const struct editorSyntaxLocalsContext *ctx,
		TSNode node) {
	if (ctx == NULL) {
		return 0;
	}
	for (int i = 0; i < ctx->count; i++) {
		if (ts_node_eq(ctx->marks[i].node, node)) {
			return ctx->marks[i].is_local != 0;
		}
	}
	return 0;
}

static int editorSyntaxScopeAddDefinition(struct editorSyntaxScopeInfo *scope,
		const char *name,
		size_t name_len) {
	if (scope == NULL || name == NULL) {
		return 0;
	}

	for (int i = 0; i < scope->def_count; i++) {
		if (strlen(scope->definitions[i]) == name_len &&
				memcmp(scope->definitions[i], name, name_len) == 0) {
			return 1;
		}
	}

	if (scope->def_count >= scope->def_cap) {
		int new_cap = scope->def_cap == 0 ? 8 : scope->def_cap * 2;
		if (new_cap <= scope->def_cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*scope->definitions);
		char **grown = realloc(scope->definitions, bytes);
		if (grown == NULL) {
			return 0;
		}
		scope->definitions = grown;
		scope->def_cap = new_cap;
	}

	char *dup = malloc(name_len + 1);
	if (dup == NULL) {
		return 0;
	}
	memcpy(dup, name, name_len);
	dup[name_len] = '\0';
	
	scope->definitions[scope->def_count] = dup;
	scope->def_count++;
	return 1;
}

static int editorSyntaxScopeHasDefinition(const struct editorSyntaxScopeInfo *scope,
		const char *name,
		size_t name_len) {
	if (scope == NULL || name == NULL) {
		return 0;
	}
	for (int i = 0; i < scope->def_count; i++) {
		if (strlen(scope->definitions[i]) == name_len &&
				memcmp(scope->definitions[i], name, name_len) == 0) {
			return 1;
		}
	}
	return 0;
}

static void editorSyntaxScopeInfoFree(struct editorSyntaxScopeInfo *scopes, int scope_count) {
	if (scopes == NULL) {
		return;
	}
	for (int i = 0; i < scope_count; i++) {
		for (int j = 0; j < scopes[i].def_count; j++) {
			free(scopes[i].definitions[j]);
		}
		free(scopes[i].definitions);
	}
	free(scopes);
}

static int editorSyntaxFindInnermostScope(const struct editorSyntaxScopeInfo *scopes,
		int scope_count,
		TSNode node) {
	int best_idx = -1;
	uint32_t best_span = UINT32_MAX;
	for (int i = 0; i < scope_count; i++) {
		if (!editorSyntaxNodeContains(scopes[i].node, node)) {
			continue;
		}
		uint32_t span = editorSyntaxNodeSpan(scopes[i].node);
		if (span < best_span) {
			best_span = span;
			best_idx = i;
		}
	}
	return best_idx;
}

static int editorSyntaxBuildLocalsContext(const TSTree *tree,
		struct editorSyntaxState *state,
		enum editorSyntaxLanguage language,
		const struct editorTextSource *source,
		struct editorSyntaxLocalsContext *ctx_out) {
	if (ctx_out == NULL) {
		return 0;
	}
	editorSyntaxLocalsContextInit(ctx_out);
	if (tree == NULL || source == NULL) {
		return 1;
	}
	if (!editorSyntaxEnsureLocalsQuery(language)) {
		return 1;
	}

	const struct editorSyntaxQueryCacheEntry *cache =
			editorSyntaxLocalsQueryCacheForLanguage(language);
	if (cache == NULL || cache->query == NULL || cache->capture_roles == NULL) {
		return 1;
	}

	TSQueryCursor *cursor = ts_query_cursor_new();
	if (cursor == NULL) {
		return 0;
	}

	TSNode root = ts_tree_root_node(tree);
	ts_query_cursor_exec(cursor, cache->query, root);

	TSNode *scope_nodes = NULL;
	TSNode *definition_nodes = NULL;
	TSNode *reference_nodes = NULL;
	int scope_count = 0;
	int scope_cap = 0;
	int definition_count = 0;
	int definition_cap = 0;
	int reference_count = 0;
	int reference_cap = 0;

	TSQueryMatch match;
	while (ts_query_cursor_next_match(cursor, &match)) {
		for (uint16_t capture_idx = 0; capture_idx < match.capture_count; capture_idx++) {
			TSQueryCapture capture = match.captures[capture_idx];
			if (capture.index >= cache->capture_count) {
				continue;
			}
			uint8_t role = cache->capture_roles[capture.index];
			if (role == EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_SCOPE) {
				if (!editorSyntaxNodeArrayAppend(&scope_nodes, &scope_count, &scope_cap,
							capture.node)) {
					goto oom;
				}
			} else if (role == EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_DEFINITION) {
				if (!editorSyntaxNodeArrayAppend(&definition_nodes, &definition_count,
							&definition_cap, capture.node)) {
					goto oom;
				}
			} else if (role == EDITOR_SYNTAX_CAPTURE_ROLE_LOCAL_REFERENCE) {
				if (!editorSyntaxNodeArrayAppend(&reference_nodes, &reference_count,
							&reference_cap, capture.node)) {
					goto oom;
				}
			}
		}
	}

	if (!editorSyntaxNodeArrayAppend(&scope_nodes, &scope_count, &scope_cap, root)) {
		goto oom;
	}

	struct editorSyntaxScopeInfo *scopes = calloc((size_t)scope_count, sizeof(*scopes));
	if (scopes == NULL) {
		goto oom;
	}

	for (int i = 0; i < scope_count; i++) {
		scopes[i].node = scope_nodes[i];
		scopes[i].parent_idx = -1;
		scopes[i].definitions = NULL;
		scopes[i].def_count = 0;
		scopes[i].def_cap = 0;
	}

	for (int i = 0; i < scope_count; i++) {
		uint32_t span_i = editorSyntaxNodeSpan(scopes[i].node);
		uint32_t best_span = UINT32_MAX;
		int best_parent = -1;
		for (int j = 0; j < scope_count; j++) {
			if (i == j) {
				continue;
			}
			if (!editorSyntaxNodeContains(scopes[j].node, scopes[i].node)) {
				continue;
			}
			uint32_t span_j = editorSyntaxNodeSpan(scopes[j].node);
			if (span_j <= span_i) {
				continue;
			}
			if (span_j < best_span) {
				best_span = span_j;
				best_parent = j;
			}
		}
		scopes[i].parent_idx = best_parent;
	}

	for (int i = 0; i < definition_count; i++) {
		const char *text = NULL;
		size_t text_len = 0;
		if (!editorSyntaxNodeText(state, source, definition_nodes[i], 0, &text, &text_len) ||
				text_len == 0) {
			continue;
		}
		int scope_idx = editorSyntaxFindInnermostScope(scopes, scope_count, definition_nodes[i]);
		if (scope_idx < 0) {
			continue;
		}
		if (!editorSyntaxScopeAddDefinition(&scopes[scope_idx], text, text_len)) {
			editorSyntaxScopeInfoFree(scopes, scope_count);
			goto oom;
		}
		if (!editorSyntaxLocalsContextMarkNode(ctx_out, definition_nodes[i], 1)) {
			editorSyntaxScopeInfoFree(scopes, scope_count);
			goto oom;
		}
	}

	for (int i = 0; i < reference_count; i++) {
		const char *text = NULL;
		size_t text_len = 0;
		if (!editorSyntaxNodeText(state, source, reference_nodes[i], 0, &text, &text_len) ||
				text_len == 0) {
			continue;
		}
		int scope_idx = editorSyntaxFindInnermostScope(scopes, scope_count, reference_nodes[i]);
		if (scope_idx < 0) {
			continue;
		}

		int is_local = 0;
		int probe = scope_idx;
		while (probe >= 0) {
			if (editorSyntaxScopeHasDefinition(&scopes[probe], text, text_len)) {
				is_local = 1;
				break;
			}
			probe = scopes[probe].parent_idx;
		}
		if (!editorSyntaxLocalsContextMarkNode(ctx_out, reference_nodes[i], is_local)) {
			editorSyntaxScopeInfoFree(scopes, scope_count);
			goto oom;
		}
	}

	editorSyntaxScopeInfoFree(scopes, scope_count);
	ts_query_cursor_delete(cursor);
	free(scope_nodes);
	free(definition_nodes);
	free(reference_nodes);
	return 1;

oom:
	ts_query_cursor_delete(cursor);
	free(scope_nodes);
	free(definition_nodes);
	free(reference_nodes);
	editorSyntaxLocalsContextFree(ctx_out);
	return 0;
}

static int editorSyntaxMatchFindCaptureNode(const TSQueryMatch *match,
		uint32_t capture_id,
		TSNode *node_out) {
	if (match == NULL || node_out == NULL) {
		return 0;
	}
	for (uint16_t i = 0; i < match->capture_count; i++) {
		if (match->captures[i].index == capture_id) {
			*node_out = match->captures[i].node;
			return 1;
		}
	}
	return 0;
}

static int editorSyntaxPredicateArgText(const TSQuery *query,
		const TSQueryMatch *match,
		const struct editorSyntaxPredicateContext *ctx,
		const TSQueryPredicateStep *arg,
		int scratch_idx,
		const char **text_out,
		size_t *len_out) {
	if (query == NULL || match == NULL || ctx == NULL || arg == NULL ||
			text_out == NULL || len_out == NULL) {
		return 0;
	}

	if (arg->type == TSQueryPredicateStepTypeString) {
		uint32_t str_len = 0;
		const char *str = ts_query_string_value_for_id(query, arg->value_id, &str_len);
		if (str == NULL) {
			return 0;
		}
		*text_out = str;
		*len_out = (size_t)str_len;
		return 1;
	}

	if (arg->type == TSQueryPredicateStepTypeCapture) {
		TSNode node;
		if (!editorSyntaxMatchFindCaptureNode(match, arg->value_id, &node)) {
			return 0;
		}
		return editorSyntaxNodeText(ctx->state, ctx->source, node, scratch_idx, text_out, len_out);
	}

	return 0;
}

static int editorSyntaxRegexMatchCompiled(const char *text, size_t text_len, regex_t *regex) {
	if (text == NULL || regex == NULL) {
		return 0;
	}

	char *text_buf = malloc(text_len + 1);
	if (text_buf == NULL) {
		free(text_buf);
		return 0;
	}
	memcpy(text_buf, text, text_len);
	text_buf[text_len] = '\0';
	int matched = regexec(regex, text_buf, 0, NULL, 0) == 0;
	free(text_buf);
	return matched;
}

static int editorSyntaxRegexMatch(const char *text, size_t text_len,
		const char *pattern, size_t pattern_len) {
	if (text == NULL || pattern == NULL) {
		return 0;
	}

	char *pattern_buf = malloc(pattern_len + 1);
	if (pattern_buf == NULL) {
		return 0;
	}
	memcpy(pattern_buf, pattern, pattern_len);
	pattern_buf[pattern_len] = '\0';

	regex_t regex;
	int compiled = regcomp(&regex, pattern_buf, REG_EXTENDED | REG_NOSUB);
	free(pattern_buf);
	if (compiled != 0) {
		return 0;
	}

	int matched = editorSyntaxRegexMatchCompiled(text, text_len, &regex);
	regfree(&regex);
	return matched;
}

static int editorSyntaxRegexMatchCached(const TSQuery *query,
		uint32_t string_id,
		const char *text,
		size_t text_len) {
	if (query == NULL || text == NULL) {
		return 0;
	}

	struct editorSyntaxQueryCacheEntry *cache = editorSyntaxQueryCacheEntryForQuery(query);
	if (cache == NULL || cache->compiled_regexes == NULL || cache->compiled_regex_compiled == NULL ||
			cache->compiled_regex_failed == NULL || string_id >= cache->string_count) {
		uint32_t pattern_len = 0;
		const char *pattern = ts_query_string_value_for_id(query, string_id, &pattern_len);
		if (pattern == NULL) {
			return 0;
		}
		return editorSyntaxRegexMatch(text, text_len, pattern, (size_t)pattern_len);
	}

	if (!cache->compiled_regex_compiled[string_id] &&
			!cache->compiled_regex_failed[string_id]) {
		uint32_t pattern_len = 0;
		const char *pattern = ts_query_string_value_for_id(query, string_id, &pattern_len);
		if (pattern == NULL) {
			cache->compiled_regex_failed[string_id] = 1;
			return 0;
		}

		char *pattern_buf = malloc((size_t)pattern_len + 1);
		if (pattern_buf == NULL) {
			return 0;
		}
		memcpy(pattern_buf, pattern, pattern_len);
		pattern_buf[pattern_len] = '\0';

		if (regcomp(&cache->compiled_regexes[string_id], pattern_buf,
					REG_EXTENDED | REG_NOSUB) == 0) {
			cache->compiled_regex_compiled[string_id] = 1;
		} else {
			cache->compiled_regex_failed[string_id] = 1;
		}
		free(pattern_buf);
	}

	if (!cache->compiled_regex_compiled[string_id]) {
		return 0;
	}

	return editorSyntaxRegexMatchCompiled(text, text_len, &cache->compiled_regexes[string_id]);
}

static int editorSyntaxPredicateTargetNode(const TSQuery *query,
		const TSQueryMatch *match,
		const TSQueryPredicateStep *args,
		uint32_t arg_count,
		TSNode *node_out,
		const char **property_out,
		size_t *property_len_out) {
	if (query == NULL || match == NULL || args == NULL || arg_count == 0 ||
			node_out == NULL || property_out == NULL || property_len_out == NULL) {
		return 0;
	}

	if (args[0].type == TSQueryPredicateStepTypeCapture) {
		if (!editorSyntaxMatchFindCaptureNode(match, args[0].value_id, node_out)) {
			return 0;
		}
		if (arg_count < 2 || args[1].type != TSQueryPredicateStepTypeString) {
			return 0;
		}
		uint32_t property_len = 0;
		const char *property = ts_query_string_value_for_id(query, args[1].value_id,
				&property_len);
		if (property == NULL) {
			return 0;
		}
		*property_out = property;
		*property_len_out = property_len;
		return 1;
	}

	if (args[0].type == TSQueryPredicateStepTypeString && match->capture_count > 0) {
		*node_out = match->captures[0].node;
		uint32_t property_len = 0;
		const char *property = ts_query_string_value_for_id(query, args[0].value_id,
				&property_len);
		if (property == NULL) {
			return 0;
		}
		*property_out = property;
		*property_len_out = property_len;
		return 1;
	}

	return 0;
}

static int editorSyntaxEvaluatePredicate(const TSQuery *query,
		const TSQueryMatch *match,
		const struct editorSyntaxPredicateContext *ctx,
		const TSQueryPredicateStep *steps,
		uint32_t step_count) {
	if (query == NULL || match == NULL || ctx == NULL || steps == NULL || step_count == 0) {
		return 1;
	}
	if (steps[0].type != TSQueryPredicateStepTypeString) {
		return 1;
	}

	uint32_t command_len = 0;
	const char *command = ts_query_string_value_for_id(query, steps[0].value_id, &command_len);
	if (command == NULL) {
		return 1;
	}

	const TSQueryPredicateStep *args = &steps[1];
	uint32_t arg_count = step_count - 1;

	if (editorSyntaxStringEquals(command, command_len, "set!")) {
		return 1;
	}

	if (editorSyntaxStringEquals(command, command_len, "eq?") ||
			editorSyntaxStringEquals(command, command_len, "not-eq?")) {
		if (arg_count < 2) {
			return 1;
		}
		const char *left = NULL;
		size_t left_len = 0;
		const char *right = NULL;
		size_t right_len = 0;
		if (!editorSyntaxPredicateArgText(query, match, ctx, &args[0], 0, &left, &left_len) ||
				!editorSyntaxPredicateArgText(query, match, ctx, &args[1], 1, &right,
						&right_len)) {
			return 0;
		}
		int equal = (left_len == right_len) && memcmp(left, right, left_len) == 0;
		if (editorSyntaxStringEquals(command, command_len, "eq?")) {
			return equal;
		}
		return !equal;
	}

	if (editorSyntaxStringEquals(command, command_len, "match?") ||
			editorSyntaxStringEquals(command, command_len, "not-match?")) {
		if (arg_count < 2) {
			return 1;
		}
		const char *text = NULL;
		size_t text_len = 0;
		const char *pattern = NULL;
		size_t pattern_len = 0;
		if (!editorSyntaxPredicateArgText(query, match, ctx, &args[0], 0, &text, &text_len) ||
				!editorSyntaxPredicateArgText(query, match, ctx, &args[1], 1, &pattern,
						&pattern_len)) {
			return 0;
		}
		int matched = 0;
		if (args[1].type == TSQueryPredicateStepTypeString) {
			matched = editorSyntaxRegexMatchCached(query, args[1].value_id, text, text_len);
		} else {
			matched = editorSyntaxRegexMatch(text, text_len, pattern, pattern_len);
		}
		if (editorSyntaxStringEquals(command, command_len, "match?")) {
			return matched;
		}
		return !matched;
	}

	if (editorSyntaxStringEquals(command, command_len, "any-of?") ||
			editorSyntaxStringEquals(command, command_len, "not-any-of?")) {
		if (arg_count < 2) {
			return 1;
		}
		const char *target = NULL;
		size_t target_len = 0;
		if (!editorSyntaxPredicateArgText(query, match, ctx, &args[0], 0, &target, &target_len)) {
			return 0;
		}

		int found = 0;
		for (uint32_t i = 1; i < arg_count; i++) {
			if (args[i].type != TSQueryPredicateStepTypeString) {
				continue;
			}
			uint32_t value_len = 0;
			const char *value = ts_query_string_value_for_id(query, args[i].value_id,
					&value_len);
			if (value == NULL) {
				continue;
			}
			if (target_len == value_len && memcmp(target, value, target_len) == 0) {
				found = 1;
				break;
			}
		}

		if (editorSyntaxStringEquals(command, command_len, "any-of?")) {
			return found;
		}
		return !found;
	}

	if (editorSyntaxStringEquals(command, command_len, "is?") ||
			editorSyntaxStringEquals(command, command_len, "is-not?")) {
		TSNode target;
		const char *property = NULL;
		size_t property_len = 0;
		if (!editorSyntaxPredicateTargetNode(query, match, args, arg_count, &target,
					&property, &property_len)) {
			return 1;
		}
		int is_property = 0;
		if (editorSyntaxStringEquals(property, property_len, "local")) {
			is_property = editorSyntaxLocalsContextNodeIsLocal(ctx->locals, target);
		}
		if (editorSyntaxStringEquals(command, command_len, "is?")) {
			return is_property;
		}
		return !is_property;
	}

	return 1;
}

static int editorSyntaxMatchPassesPredicates(const TSQuery *query,
		uint32_t pattern_index,
		const TSQueryMatch *match,
		const struct editorSyntaxPredicateContext *ctx) {
	if (query == NULL || match == NULL || ctx == NULL) {
		return 1;
	}

	uint32_t step_count = 0;
	const TSQueryPredicateStep *steps = ts_query_predicates_for_pattern(query, pattern_index,
			&step_count);
	if (steps == NULL || step_count == 0) {
		return 1;
	}

	uint32_t i = 0;
	while (i < step_count) {
		uint32_t start = i;
		while (i < step_count && steps[i].type != TSQueryPredicateStepTypeDone) {
			i++;
		}
		uint32_t end = i;
		if (end > start) {
			if (!editorSyntaxEvaluatePredicate(query, match, ctx, &steps[start], end - start)) {
				return 0;
			}
		}
		i++;
	}

	return 1;
}

static int editorSyntaxCaptureVecAppend(struct editorSyntaxCaptureVec *vec,
		uint32_t start_byte,
		uint32_t end_byte,
		enum editorSyntaxHighlightClass highlight_class) {
	if (vec == NULL) {
		return 0;
	}
	if (vec->count >= vec->cap) {
		int new_cap = vec->cap == 0 ? 128 : vec->cap * 2;
		if (new_cap <= vec->cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*vec->items);
		struct editorSyntaxCapture *grown = realloc(vec->items, bytes);
		if (grown == NULL) {
			return 0;
		}
		vec->items = grown;
		vec->cap = new_cap;
	}

	vec->items[vec->count].start_byte = start_byte;
	vec->items[vec->count].end_byte = end_byte;
	vec->items[vec->count].highlight_class = highlight_class;
	vec->count++;
	return 1;
}

static void editorSyntaxCaptureVecFree(struct editorSyntaxCaptureVec *vec) {
	if (vec == NULL) {
		return;
	}
	free(vec->items);
	vec->items = NULL;
	vec->count = 0;
	vec->cap = 0;
}

static int editorSyntaxCollectCapturesFromTree(struct editorSyntaxState *state,
		const TSTree *tree,
		enum editorSyntaxLanguage language,
		const struct editorTextSource *source,
		uint32_t start_byte,
		uint32_t end_byte,
		const struct editorSyntaxLocalsContext *locals,
		int skip_predicates,
		struct editorSyntaxCaptureVec *captures_out) {
	if (captures_out == NULL) {
		return 0;
	}
	if (tree == NULL || start_byte >= end_byte) {
		return 1;
	}

	if (!editorSyntaxEnsureHighlightQuery(language)) {
		return 1;
	}
	const struct editorSyntaxQueryCacheEntry *cache =
			editorSyntaxHighlightQueryCacheForLanguage(language);
	if (cache == NULL || cache->query == NULL || cache->capture_classes == NULL) {
		return 1;
	}

	TSQueryCursor *cursor = ts_query_cursor_new();
	if (cursor == NULL) {
		return 0;
	}

	TSNode root = ts_tree_root_node(tree);
	ts_query_cursor_set_byte_range(cursor, start_byte, end_byte);
	struct editorSyntaxBudgetConfig budget =
			editorSyntaxBudgetConfigForMode(state != NULL ? state->perf_mode :
					EDITOR_SYNTAX_PERF_NORMAL);
	if (budget.query_match_limit > 0) {
		ts_query_cursor_set_match_limit(cursor, budget.query_match_limit);
	}
	struct editorSyntaxDeadlineContext query_deadline = {0};
	TSQueryCursorOptions query_options = {0};
	if (budget.query_budget_ns > 0) {
		query_deadline.deadline_ns = editorSyntaxComputeDeadlineNs(budget.query_budget_ns);
		query_options.payload = &query_deadline;
		query_options.progress_callback = editorSyntaxQueryProgressCallback;
		ts_query_cursor_exec_with_options(cursor, cache->query, root, &query_options);
	} else {
		ts_query_cursor_exec(cursor, cache->query, root);
	}

	struct editorSyntaxPredicateContext predicate_ctx = {
		.state = state,
		.source = source,
		.locals = locals
	};

	TSQueryMatch match;
	uint32_t capture_idx = 0;
	while (ts_query_cursor_next_capture(cursor, &match, &capture_idx)) {
		if (!skip_predicates &&
				!editorSyntaxMatchPassesPredicates(cache->query, match.pattern_index, &match,
						&predicate_ctx)) {
			continue;
		}
		if (capture_idx >= match.capture_count) {
			continue;
		}
		TSQueryCapture capture = match.captures[capture_idx];
		if (capture.index >= cache->capture_count) {
			continue;
		}
		enum editorSyntaxHighlightClass highlight_class =
				cache->capture_classes[capture.index];
		if (highlight_class == EDITOR_SYNTAX_HL_NONE) {
			continue;
		}

		uint32_t capture_start = ts_node_start_byte(capture.node);
		uint32_t capture_end = ts_node_end_byte(capture.node);
		if (capture_end <= capture_start) {
			continue;
		}
		if (capture_end <= start_byte || capture_start >= end_byte) {
			continue;
		}
		if (capture_start < start_byte) {
			capture_start = start_byte;
		}
		if (capture_end > end_byte) {
			capture_end = end_byte;
		}
		if (capture_end <= capture_start) {
			continue;
		}

		if (!editorSyntaxCaptureVecAppend(captures_out, capture_start, capture_end,
					highlight_class)) {
			ts_query_cursor_delete(cursor);
			return 0;
		}
	}

	if (state != NULL) {
		if (query_deadline.exceeded) {
			state->budget_query_exceeded = 1;
		}
		if (ts_query_cursor_did_exceed_match_limit(cursor)) {
			state->budget_query_exceeded = 1;
		}
	}

	ts_query_cursor_delete(cursor);
	return 1;
}

static int editorSyntaxRangeVecAppend(struct editorSyntaxRangeVec *ranges, const TSRange *range) {
	if (ranges == NULL || range == NULL) {
		return 0;
	}
	if (ranges->count >= ranges->cap) {
		uint32_t new_cap = ranges->cap == 0 ? 16 : ranges->cap * 2;
		if (new_cap <= ranges->cap) {
			return 0;
		}
		size_t bytes = (size_t)new_cap * sizeof(*ranges->items);
		TSRange *grown = realloc(ranges->items, bytes);
		if (grown == NULL) {
			return 0;
		}
		ranges->items = grown;
		ranges->cap = new_cap;
	}
	ranges->items[ranges->count] = *range;
	ranges->count++;
	return 1;
}

static void editorSyntaxRangeVecFree(struct editorSyntaxRangeVec *ranges) {
	if (ranges == NULL) {
		return;
	}
	free(ranges->items);
	ranges->items = NULL;
	ranges->count = 0;
	ranges->cap = 0;
}

static int editorSyntaxCompareRange(const void *a, const void *b) {
	const TSRange *left = a;
	const TSRange *right = b;
	if (left->start_byte < right->start_byte) {
		return -1;
	}
	if (left->start_byte > right->start_byte) {
		return 1;
	}
	if (left->end_byte < right->end_byte) {
		return -1;
	}
	if (left->end_byte > right->end_byte) {
		return 1;
	}
	return 0;
}

static enum editorSyntaxLanguage editorSyntaxLanguageFromInjectionName(const char *name,
		size_t len) {
	if (editorSyntaxStringEqualsNoCase(name, len, "javascript") ||
			editorSyntaxStringEqualsNoCase(name, len, "js")) {
		return EDITOR_SYNTAX_JAVASCRIPT;
	}
	if (editorSyntaxStringEqualsNoCase(name, len, "css")) {
		return EDITOR_SYNTAX_CSS;
	}
	return EDITOR_SYNTAX_NONE;
}

static int editorSyntaxCollectHtmlInjectionRanges(struct editorSyntaxState *state,
		const struct editorTextSource *source,
		struct editorSyntaxRangeVec *javascript_ranges,
		struct editorSyntaxRangeVec *css_ranges) {
	if (state == NULL || source == NULL || javascript_ranges == NULL || css_ranges == NULL) {
		return 0;
	}
	if (state->host.tree == NULL) {
		return 1;
	}
	if (!editorSyntaxEnsureHtmlInjectionQuery()) {
		return 1;
	}

	const struct editorSyntaxQueryCacheEntry *cache = &g_html_injection_query_cache;
	if (cache->query == NULL || cache->capture_roles == NULL ||
			cache->pattern_injection_languages == NULL) {
		return 1;
	}

	TSQueryCursor *cursor = ts_query_cursor_new();
	if (cursor == NULL) {
		return 0;
	}

	TSNode root = ts_tree_root_node(state->host.tree);
	struct editorSyntaxBudgetConfig budget =
			editorSyntaxBudgetConfigForMode(state->perf_mode);
	if (budget.query_match_limit > 0) {
		ts_query_cursor_set_match_limit(cursor, budget.query_match_limit);
	}
	struct editorSyntaxDeadlineContext query_deadline = {0};
	TSQueryCursorOptions query_options = {0};
	if (budget.query_budget_ns > 0) {
		query_deadline.deadline_ns = editorSyntaxComputeDeadlineNs(budget.query_budget_ns);
		query_options.payload = &query_deadline;
		query_options.progress_callback = editorSyntaxQueryProgressCallback;
		ts_query_cursor_exec_with_options(cursor, cache->query, root, &query_options);
	} else {
		ts_query_cursor_exec(cursor, cache->query, root);
	}

	struct editorSyntaxPredicateContext predicate_ctx = {
		.state = state,
		.source = source,
		.locals = NULL
	};

	TSQueryMatch match;
	while (ts_query_cursor_next_match(cursor, &match)) {
		if (match.pattern_index >= cache->pattern_count) {
			continue;
		}
		if (!state->perf_disable_predicates &&
				!editorSyntaxMatchPassesPredicates(cache->query, match.pattern_index, &match,
						&predicate_ctx)) {
			continue;
		}

		const char *lang_name = cache->pattern_injection_languages[match.pattern_index];
		if (lang_name == NULL) {
			continue;
		}
		enum editorSyntaxLanguage target_lang =
				editorSyntaxLanguageFromInjectionName(lang_name, strlen(lang_name));
		if (target_lang != EDITOR_SYNTAX_JAVASCRIPT && target_lang != EDITOR_SYNTAX_CSS) {
			continue;
		}

		for (uint16_t capture_idx = 0; capture_idx < match.capture_count; capture_idx++) {
			TSQueryCapture capture = match.captures[capture_idx];
			if (capture.index >= cache->capture_count) {
				continue;
			}
			if (cache->capture_roles[capture.index] !=
					EDITOR_SYNTAX_CAPTURE_ROLE_INJECTION_CONTENT) {
				continue;
			}

			TSRange range = {
				.start_point = ts_node_start_point(capture.node),
				.end_point = ts_node_end_point(capture.node),
				.start_byte = ts_node_start_byte(capture.node),
				.end_byte = ts_node_end_byte(capture.node)
			};
			if (range.end_byte <= range.start_byte) {
				continue;
			}

			int ok = 0;
			if (target_lang == EDITOR_SYNTAX_JAVASCRIPT) {
				ok = editorSyntaxRangeVecAppend(javascript_ranges, &range);
			} else {
				ok = editorSyntaxRangeVecAppend(css_ranges, &range);
			}
			if (!ok) {
				ts_query_cursor_delete(cursor);
				return 0;
			}
		}
	}

	if (query_deadline.exceeded || ts_query_cursor_did_exceed_match_limit(cursor)) {
		state->budget_query_exceeded = 1;
	}

	ts_query_cursor_delete(cursor);
	if (javascript_ranges->count > 1) {
		qsort(javascript_ranges->items, javascript_ranges->count,
				sizeof(javascript_ranges->items[0]), editorSyntaxCompareRange);
	}
	if (css_ranges->count > 1) {
		qsort(css_ranges->items, css_ranges->count,
				sizeof(css_ranges->items[0]), editorSyntaxCompareRange);
	}
	return 1;
}

static void editorSyntaxApplyInputEdit(TSTree *tree, const struct editorSyntaxEdit *edit) {
	if (tree == NULL || edit == NULL) {
		return;
	}
	TSInputEdit ts_edit = {
		.start_byte = edit->start_byte,
		.old_end_byte = edit->old_end_byte,
		.new_end_byte = edit->new_end_byte,
		.start_point = {.row = edit->start_point.row, .column = edit->start_point.column},
		.old_end_point = {.row = edit->old_end_point.row, .column = edit->old_end_point.column},
		.new_end_point = {.row = edit->new_end_point.row, .column = edit->new_end_point.column}
	};
	ts_tree_edit(tree, &ts_edit);
}

static int editorSyntaxStateParseHtmlInjections(struct editorSyntaxState *state,
		const struct editorTextSource *source,
		const struct editorSyntaxEdit *incremental_edit) {
	if (state == NULL || source == NULL) {
		return 0;
	}
	if (state->language != EDITOR_SYNTAX_HTML) {
		return 1;
	}
	if (state->perf_disable_injections) {
		if (!editorSyntaxParsedTreeSetIncludedRanges(&state->javascript_injection, NULL, 0) ||
				!editorSyntaxParsedTreeSetIncludedRanges(&state->css_injection, NULL, 0)) {
			return 0;
		}
		editorSyntaxParsedTreeResetTree(&state->javascript_injection);
		editorSyntaxParsedTreeResetTree(&state->css_injection);
		return 1;
	}

	struct editorSyntaxRangeVec javascript_ranges = {0};
	struct editorSyntaxRangeVec css_ranges = {0};
	if (!editorSyntaxCollectHtmlInjectionRanges(state, source, &javascript_ranges, &css_ranges)) {
		editorSyntaxRangeVecFree(&javascript_ranges);
		editorSyntaxRangeVecFree(&css_ranges);
		return 0;
	}

	if (incremental_edit != NULL) {
		if (state->javascript_injection.tree != NULL) {
			editorSyntaxApplyInputEdit(state->javascript_injection.tree, incremental_edit);
		}
		if (state->css_injection.tree != NULL) {
			editorSyntaxApplyInputEdit(state->css_injection.tree, incremental_edit);
		}
	}

	if (!editorSyntaxParsedTreeSetIncludedRanges(&state->javascript_injection,
			javascript_ranges.items, javascript_ranges.count) ||
			!editorSyntaxParsedTreeSetIncludedRanges(&state->css_injection,
					css_ranges.items, css_ranges.count)) {
		editorSyntaxRangeVecFree(&javascript_ranges);
		editorSyntaxRangeVecFree(&css_ranges);
		return 0;
	}

	if (javascript_ranges.count == 0) {
		editorSyntaxParsedTreeResetTree(&state->javascript_injection);
	}
	if (css_ranges.count == 0) {
		editorSyntaxParsedTreeResetTree(&state->css_injection);
	}

	int ok = 1;
	if (javascript_ranges.count > 0) {
		int incremental = incremental_edit != NULL &&
				state->javascript_injection.tree != NULL;
		ok = editorSyntaxParsedTreeParse(&state->javascript_injection, NULL, source, incremental);
	}
	if (ok && css_ranges.count > 0) {
		int incremental = incremental_edit != NULL &&
				state->css_injection.tree != NULL;
		ok = editorSyntaxParsedTreeParse(&state->css_injection, NULL, source, incremental);
	}

	editorSyntaxRangeVecFree(&javascript_ranges);
	editorSyntaxRangeVecFree(&css_ranges);
	return ok;
}

static void editorSyntaxStateInvalidateLocalsCaches(struct editorSyntaxState *state) {
	if (state == NULL) {
		return;
	}
	state->host_javascript_locals_valid = 0;
	state->injection_javascript_locals_valid = 0;
}

static int editorSyntaxStateEnsureJavascriptLocalsCached(
		struct editorSyntaxState *state,
		const struct editorSyntaxParsedTree *parsed,
		const struct editorTextSource *source,
		int injection_tree,
		const struct editorSyntaxLocalsContext **locals_out) {
	if (locals_out == NULL) {
		return 0;
	}
	*locals_out = NULL;

	if (state == NULL || parsed == NULL || parsed->tree == NULL || source == NULL) {
		return 1;
	}

	struct editorSyntaxLocalsContext *cache = injection_tree ?
			&state->injection_javascript_locals :
			&state->host_javascript_locals;
	uint64_t *cache_revision = injection_tree ?
			&state->injection_javascript_locals_revision :
			&state->host_javascript_locals_revision;
	int *cache_valid = injection_tree ?
			&state->injection_javascript_locals_valid :
			&state->host_javascript_locals_valid;

	if (*cache_valid && *cache_revision == parsed->revision) {
		*locals_out = cache;
		return 1;
	}

	editorSyntaxLocalsContextFree(cache);
	editorSyntaxLocalsContextInit(cache);
	if (!editorSyntaxBuildLocalsContext(parsed->tree, state, EDITOR_SYNTAX_JAVASCRIPT, source,
				cache)) {
		editorSyntaxLocalsContextFree(cache);
		*cache_valid = 0;
		return 0;
	}

	*cache_revision = parsed->revision;
	*cache_valid = 1;
	*locals_out = cache;
	return 1;
}

static void editorSyntaxStateApplyPerformanceMode(struct editorSyntaxState *state,
		size_t source_len) {
	if (state == NULL) {
		return;
	}

	enum editorSyntaxPerformanceMode mode = EDITOR_SYNTAX_PERF_NORMAL;
	int disable_predicates = 0;
	int disable_injections = 0;

	if (source_len > ROTIDE_SYNTAX_PERF_DEGRADED_INJECTIONS_BYTES) {
		mode = EDITOR_SYNTAX_PERF_DEGRADED_INJECTIONS;
		disable_predicates = 1;
		disable_injections = 1;
	} else if (source_len > ROTIDE_SYNTAX_PERF_DEGRADED_PREDICATES_BYTES) {
		mode = EDITOR_SYNTAX_PERF_DEGRADED_PREDICATES;
		disable_predicates = 1;
	}

	if (state->perf_disable_predicates != disable_predicates) {
		editorSyntaxStateInvalidateLocalsCaches(state);
	}
	state->perf_disable_predicates = disable_predicates;
	state->perf_disable_injections = disable_injections;
	state->perf_mode = mode;
}

int editorSyntaxStateConfigureForSourceLength(struct editorSyntaxState *state, size_t source_len) {
	if (state == NULL) {
		return 0;
	}
	editorSyntaxStateApplyPerformanceMode(state, source_len);
	return editorSyntaxLengthFitsTreeSitter(source_len);
}

enum editorSyntaxPerformanceMode editorSyntaxStatePerformanceMode(
		const struct editorSyntaxState *state) {
	if (state == NULL) {
		return EDITOR_SYNTAX_PERF_NORMAL;
	}
	return state->perf_mode;
}

size_t editorSyntaxStateSourceLength(const struct editorSyntaxState *state) {
	if (state == NULL) {
		return 0;
	}
	return state->source_len;
}

struct editorSyntaxState *editorSyntaxStateCreate(enum editorSyntaxLanguage language) {
	const TSLanguage *host_language = editorSyntaxLanguageObject(language);
	if (host_language == NULL) {
		return NULL;
	}
	(void)host_language;

	struct editorSyntaxState *state = malloc(sizeof(*state));
	if (state == NULL) {
		return NULL;
	}
	state->language = language;
	editorSyntaxParsedTreeInit(&state->host, language);
	editorSyntaxParsedTreeInit(&state->javascript_injection, EDITOR_SYNTAX_JAVASCRIPT);
	editorSyntaxParsedTreeInit(&state->css_injection, EDITOR_SYNTAX_CSS);
	editorSyntaxLocalsContextInit(&state->host_javascript_locals);
	editorSyntaxLocalsContextInit(&state->injection_javascript_locals);
	state->host_javascript_locals_revision = 0;
	state->injection_javascript_locals_revision = 0;
	state->host_javascript_locals_valid = 0;
	state->injection_javascript_locals_valid = 0;
	state->perf_disable_predicates = 0;
	state->perf_disable_injections = 0;
	state->perf_mode = EDITOR_SYNTAX_PERF_NORMAL;
	state->last_changed_ranges = NULL;
	state->last_changed_range_count = 0;
	state->last_changed_range_cap = 0;
	state->budget_parse_exceeded = 0;
	state->budget_query_exceeded = 0;
	state->source_len = 0;
	state->scratch_primary = NULL;
	state->scratch_primary_cap = 0;
	state->scratch_secondary = NULL;
	state->scratch_secondary_cap = 0;

	if (!editorSyntaxParsedTreeCreateParser(&state->host, language)) {
		free(state);
		return NULL;
	}

	if (language == EDITOR_SYNTAX_HTML) {
		if (!editorSyntaxParsedTreeCreateParser(&state->javascript_injection,
					EDITOR_SYNTAX_JAVASCRIPT) ||
				!editorSyntaxParsedTreeCreateParser(&state->css_injection,
						EDITOR_SYNTAX_CSS)) {
			editorSyntaxParsedTreeDestroy(&state->host);
			editorSyntaxParsedTreeDestroy(&state->javascript_injection);
			editorSyntaxParsedTreeDestroy(&state->css_injection);
			editorSyntaxLocalsContextFree(&state->host_javascript_locals);
			editorSyntaxLocalsContextFree(&state->injection_javascript_locals);
			free(state->last_changed_ranges);
			free(state->scratch_primary);
			free(state->scratch_secondary);
			free(state);
			return NULL;
		}
	}

	return state;
}

void editorSyntaxStateDestroy(struct editorSyntaxState *state) {
	if (state == NULL) {
		return;
	}
	editorSyntaxParsedTreeDestroy(&state->host);
	editorSyntaxParsedTreeDestroy(&state->javascript_injection);
	editorSyntaxParsedTreeDestroy(&state->css_injection);
	editorSyntaxLocalsContextFree(&state->host_javascript_locals);
	editorSyntaxLocalsContextFree(&state->injection_javascript_locals);
	free(state->last_changed_ranges);
	state->last_changed_ranges = NULL;
	state->last_changed_range_count = 0;
	state->last_changed_range_cap = 0;
	free(state->scratch_primary);
	state->scratch_primary = NULL;
	state->scratch_primary_cap = 0;
	free(state->scratch_secondary);
	state->scratch_secondary = NULL;
	state->scratch_secondary_cap = 0;
	state->source_len = 0;
	free(state);
}

int editorSyntaxStateParseFull(struct editorSyntaxState *state,
		const struct editorTextSource *source) {
	if (state == NULL || source == NULL || source->read == NULL ||
			!editorSyntaxLengthFitsTreeSitter(source->length)) {
		return 0;
	}
	state->budget_parse_exceeded = 0;
	state->budget_query_exceeded = 0;
	editorSyntaxStateClearChangedRanges(state);
	editorSyntaxStateApplyPerformanceMode(state, source->length);

	if (!editorSyntaxParsedTreeParse(&state->host, state, source, 0)) {
		return 0;
	}
	if (!editorSyntaxStateParseHtmlInjections(state, source, NULL)) {
		return 0;
	}
	state->source_len = source->length;
	if (!editorSyntaxStateSetChangedRangesFull(state, source->length)) {
		return 0;
	}
	return 1;
}

int editorSyntaxStateApplyEditAndParse(struct editorSyntaxState *state,
		const struct editorSyntaxEdit *edit,
		const struct editorTextSource *source) {
	if (state == NULL || edit == NULL || source == NULL || source->read == NULL ||
			!editorSyntaxLengthFitsTreeSitter(source->length) ||
			state->host.parser == NULL || state->host.tree == NULL) {
		return 0;
	}
	state->budget_parse_exceeded = 0;
	state->budget_query_exceeded = 0;
	editorSyntaxStateClearChangedRanges(state);
	if ((size_t)edit->old_end_byte > state->source_len || edit->old_end_byte < edit->start_byte) {
		return 0;
	}
	editorSyntaxStateApplyPerformanceMode(state, source->length);

	editorSyntaxApplyInputEdit(state->host.tree, edit);
	if (!editorSyntaxParsedTreeParse(&state->host, state, source, 1)) {
		return 0;
	}
	if (!editorSyntaxStateParseHtmlInjections(state, source, edit)) {
		return 0;
	}
	state->source_len = source->length;
	return 1;
}

int editorSyntaxStateHasTree(const struct editorSyntaxState *state) {
	return state != NULL && state->host.tree != NULL;
}

const char *editorSyntaxStateRootType(const struct editorSyntaxState *state) {
	if (state == NULL || state->host.tree == NULL) {
		return NULL;
	}
	TSNode root = ts_tree_root_node(state->host.tree);
	return ts_node_type(root);
}

enum editorSyntaxLanguage editorSyntaxStateLanguage(const struct editorSyntaxState *state) {
	if (state == NULL) {
		return EDITOR_SYNTAX_NONE;
	}
	return state->language;
}

static int editorSyntaxCaptureSortKeyCmp(const struct editorSyntaxCapture *left,
		const struct editorSyntaxCapture *right) {
	if (left->start_byte < right->start_byte) {
		return -1;
	}
	if (left->start_byte > right->start_byte) {
		return 1;
	}
	if (left->end_byte < right->end_byte) {
		return -1;
	}
	if (left->end_byte > right->end_byte) {
		return 1;
	}
	return 0;
}

int editorSyntaxStateCollectCapturesForRange(struct editorSyntaxState *state,
		const struct editorTextSource *source,
		uint32_t start_byte,
		uint32_t end_byte,
		struct editorSyntaxCapture *captures,
		int max_captures,
		int *count_out) {
	if (count_out != NULL) {
		*count_out = 0;
	}
	if (state == NULL || source == NULL || source->read == NULL || start_byte >= end_byte ||
			max_captures < 0 ||
			(max_captures > 0 && captures == NULL)) {
		return 0;
	}
	if (max_captures == 0 || state->host.tree == NULL) {
		return 1;
	}
	int skip_predicates = state->perf_disable_predicates;

	if (state->language != EDITOR_SYNTAX_HTML) {
		struct editorSyntaxCaptureVec collected = {0};
		const struct editorSyntaxLocalsContext *host_js_locals = NULL;
		if (!skip_predicates && state->language == EDITOR_SYNTAX_JAVASCRIPT &&
				!editorSyntaxStateEnsureJavascriptLocalsCached(state, &state->host, source, 0,
						&host_js_locals)) {
			editorSyntaxCaptureVecFree(&collected);
			return 0;
		}

		int ok = editorSyntaxCollectCapturesFromTree(state, state->host.tree, state->language,
				source, start_byte, end_byte, host_js_locals, skip_predicates, &collected);
		if (!ok) {
			editorSyntaxCaptureVecFree(&collected);
			return 0;
		}

		int out_count = collected.count;
		if (out_count > max_captures) {
			out_count = max_captures;
		}
		for (int i = 0; i < out_count; i++) {
			captures[i] = collected.items[i];
		}
		if (count_out != NULL) {
			*count_out = out_count;
		}
		editorSyntaxCaptureVecFree(&collected);
		return 1;
	}

	struct editorSyntaxCaptureVec host_captures = {0};
	struct editorSyntaxCaptureVec js_captures = {0};
	struct editorSyntaxCaptureVec css_captures = {0};
	const struct editorSyntaxLocalsContext *host_js_locals = NULL;
	if (!skip_predicates && state->language == EDITOR_SYNTAX_JAVASCRIPT &&
			!editorSyntaxStateEnsureJavascriptLocalsCached(state, &state->host, source, 0,
					&host_js_locals)) {
		editorSyntaxCaptureVecFree(&host_captures);
		editorSyntaxCaptureVecFree(&js_captures);
		editorSyntaxCaptureVecFree(&css_captures);
		return 0;
	}

	int ok = editorSyntaxCollectCapturesFromTree(state, state->host.tree, state->language,
			source, start_byte, end_byte, host_js_locals, skip_predicates, &host_captures);
	if (!ok) {
		editorSyntaxCaptureVecFree(&host_captures);
		editorSyntaxCaptureVecFree(&js_captures);
		editorSyntaxCaptureVecFree(&css_captures);
		return 0;
	}

	if (state->language == EDITOR_SYNTAX_HTML && !state->perf_disable_injections) {
		const struct editorSyntaxLocalsContext *injection_js_locals = NULL;
		if (!skip_predicates &&
				!editorSyntaxStateEnsureJavascriptLocalsCached(state, &state->javascript_injection,
						source, 1, &injection_js_locals)) {
			editorSyntaxCaptureVecFree(&host_captures);
			editorSyntaxCaptureVecFree(&js_captures);
			editorSyntaxCaptureVecFree(&css_captures);
			return 0;
		}
		if (!editorSyntaxCollectCapturesFromTree(state, state->javascript_injection.tree,
					EDITOR_SYNTAX_JAVASCRIPT, source, start_byte, end_byte,
					injection_js_locals, skip_predicates, &js_captures) ||
				!editorSyntaxCollectCapturesFromTree(state, state->css_injection.tree,
						EDITOR_SYNTAX_CSS, source, start_byte, end_byte,
						NULL, skip_predicates, &css_captures)) {
			editorSyntaxCaptureVecFree(&host_captures);
			editorSyntaxCaptureVecFree(&js_captures);
			editorSyntaxCaptureVecFree(&css_captures);
			return 0;
		}
	}

	int idx_host = 0;
	int idx_js = 0;
	int idx_css = 0;
	int out_count = 0;
	while (out_count < max_captures &&
			(idx_host < host_captures.count || idx_js < js_captures.count ||
					idx_css < css_captures.count)) {
		int source_choice = -1;
		const struct editorSyntaxCapture *choice = NULL;

		if (idx_host < host_captures.count) {
			choice = &host_captures.items[idx_host];
			source_choice = 0;
		}
		if (idx_js < js_captures.count) {
			const struct editorSyntaxCapture *candidate = &js_captures.items[idx_js];
			if (choice == NULL || editorSyntaxCaptureSortKeyCmp(candidate, choice) < 0) {
				choice = candidate;
				source_choice = 1;
			}
		}
		if (idx_css < css_captures.count) {
			const struct editorSyntaxCapture *candidate = &css_captures.items[idx_css];
			if (choice == NULL || editorSyntaxCaptureSortKeyCmp(candidate, choice) < 0) {
				choice = candidate;
				source_choice = 2;
			}
		}

		if (choice == NULL || source_choice < 0) {
			break;
		}
		captures[out_count++] = *choice;
		if (source_choice == 0) {
			idx_host++;
		} else if (source_choice == 1) {
			idx_js++;
		} else {
			idx_css++;
		}
	}

	if (count_out != NULL) {
		*count_out = out_count;
	}
	editorSyntaxCaptureVecFree(&host_captures);
	editorSyntaxCaptureVecFree(&js_captures);
	editorSyntaxCaptureVecFree(&css_captures);
	return 1;
}

int editorSyntaxStateCopyLastChangedRanges(const struct editorSyntaxState *state,
		struct editorSyntaxByteRange *ranges, int max_ranges, int *count_out) {
	if (count_out != NULL) {
		*count_out = 0;
	}
	if (state == NULL || max_ranges < 0 || (max_ranges > 0 && ranges == NULL)) {
		return 0;
	}

	int total_count = state->last_changed_range_count;
	int copy_count = total_count;
	if (copy_count > max_ranges) {
		copy_count = max_ranges;
	}
	for (int i = 0; i < copy_count; i++) {
		ranges[i] = state->last_changed_ranges[i];
	}
	if (count_out != NULL) {
		*count_out = total_count;
	}
	return 1;
}

int editorSyntaxStateConsumeBudgetEvents(struct editorSyntaxState *state,
		int *parse_budget_exceeded_out,
		int *query_budget_exceeded_out) {
	if (parse_budget_exceeded_out != NULL) {
		*parse_budget_exceeded_out = 0;
	}
	if (query_budget_exceeded_out != NULL) {
		*query_budget_exceeded_out = 0;
	}
	if (state == NULL) {
		return 0;
	}

	if (parse_budget_exceeded_out != NULL) {
		*parse_budget_exceeded_out = state->budget_parse_exceeded;
	}
	if (query_budget_exceeded_out != NULL) {
		*query_budget_exceeded_out = state->budget_query_exceeded;
	}

	int had = state->budget_parse_exceeded || state->budget_query_exceeded;
	state->budget_parse_exceeded = 0;
	state->budget_query_exceeded = 0;
	return had;
}

void editorSyntaxTestSetBudgetOverrides(int enabled,
		uint32_t query_match_limit,
		uint64_t query_time_budget_ns,
		uint64_t parse_time_budget_ns) {
	g_editor_syntax_budget_overrides.enabled = enabled ? 1 : 0;
	g_editor_syntax_budget_overrides.query_match_limit = query_match_limit;
	g_editor_syntax_budget_overrides.query_time_budget_ns = query_time_budget_ns;
	g_editor_syntax_budget_overrides.parse_time_budget_ns = parse_time_budget_ns;
}

void editorSyntaxTestResetBudgetOverrides(void) {
	memset(&g_editor_syntax_budget_overrides, 0, sizeof(g_editor_syntax_budget_overrides));
}

int editorSyntaxTestBudgetOverridesEnabled(void) {
	return g_editor_syntax_budget_overrides.enabled;
}

void editorSyntaxReleaseSharedResources(void) {
	editorSyntaxClearQueryCacheEntry(&g_c_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_cpp_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_go_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_shell_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_html_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_javascript_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_css_highlight_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_javascript_locals_query_cache);
	editorSyntaxClearQueryCacheEntry(&g_html_injection_query_cache);
}
